MyOnlineStore/bricks

config/jest/jest.config.json, config/storybook/decorators/themeDecorator.tsx, config/typescript/tslint.json, package-lock.json, package.json, src/__snapshots__/index.test.ts.snap, src/components/Button/Button.style.tsx, src/components/FoldOut/FoldOut.story.tsx, src/components/FoldOut/FoldOut.style.tsx, src/components/FoldOut/FoldOut.template.tsx, src/components/FoldOut/FoldOut.test.tsx, src/components/FoldOut/index.ts, src/components/Icon/Icon.style.tsx, src/components/Spacer/Spacer.template.tsx, src/index.test.ts, src/utility/styled/index.ts
This Pr adds:
- The `FoldOut` component
- A `StyledType` that defines the injected props by styled-components
=> FoldOut component

package.json, src/__snapshots__/index.test.ts.snap, src/components/Button/Button.style.tsx, src/components/Button/Button.template.tsx, src/components/FlatButton/FlatButton.story.tsx, src/components/FlatButton/FlatButton.style.tsx, src/components/FlatButton/index.ts, src/themes.ts
This pr adds:
- a FlatButton component for text style buttons.
- nested ThemeType properties for readability.
=> Added FlatButton component, adjusted themeType

src/components/Icon/Icon.style.tsx, src/index.ts
**Adds** ✨
- `FlatButton` to the index file for distribution
**Changes** 🌀
- Props interpolation on styled `Icon`
=> Fixed Icon interpolation bug

config/typescript/tslint.json, package-lock.json, package.json, src/__snapshots__/index.test.ts.snap, src/components/BreakpointProvider/BreakpointProvider.story.tsx, src/components/Button/Button.test.tsx, src/components/FoldOut/FoldOut.story.tsx, src/components/Icon/Icon.template.tsx, src/components/Icon/index.ts, src/components/Notification/Notification.story.tsx, src/components/Notification/Notification.style.tsx, src/components/Notification/Notification.template.tsx, src/components/Notification/index.ts, src/components/Spacer/Spacer.story.tsx, src/index.ts, src/themes/MosTheme/MosTheme.theme.ts, src/themes/types/NotificationThemeType.ts, src/themes/types/ThemeType.ts
**Adds** ✨
- The `Notification` component
**Changes** 🌀
- A few stories so they use styled text according to the theme.
=> Added Notification

src/__snapshots__/index.test.ts.snap, src/components/Button/Button.style.tsx
=> Fixed disabled Button background transition

src/__snapshots__/index.test.ts.snap, src/components/PriceTag/PriceTag.story.tsx, src/components/PriceTag/PriceTag.style.tsx, src/components/PriceTag/PriceTag.template.tsx, src/components/PriceTag/PriceTag.test.tsx, src/components/PriceTag/__snapshots__/PriceTag.test.tsx.snap, src/components/PriceTag/formatters/formatCurrency.ts, src/components/PriceTag/formatters/formatDecimalSeperator.ts, src/components/PriceTag/formatters/formatFraction.tsx, src/components/PriceTag/index.ts, src/themes/MosTheme/MosTheme.theme.ts, src/themes/types/ThemeType.ts
**Adds** ✨
- A `PriceTag` component.
- A few keys to the theme.
=> Added PriceTag component

src/index.ts
**Adds** ✨
- `PriceTag` to the main index.
=> Added pricetag to main index

package-lock.json, package.json, src/__snapshots__/index.test.ts.snap, src/components/PriceTag/PriceTag.story.tsx, src/components/PriceTag/PriceTag.style.tsx, src/components/PriceTag/PriceTag.template.tsx, src/components/PriceTag/PriceTag.test.tsx, src/components/PriceTag/__snapshots__/PriceTag.test.tsx.snap, src/themes/MosTheme/MosTheme.theme.ts, src/themes/types/ThemeType.ts
**Adds** ✨
- `isActionPrice` prop to `PriceTag`
- `freeLabel` props to `PriceTag` that renders a text when the price is 0
=> Added actionprice and free label

.circleci/config.yml, config/webpack/webpack.config.js, package-lock.json, package.json
**Adds** ✨
- The `uglify-webpack-plugin`
**Changes** 🌀
- Dist artifacts to be minified and without sourcemaps
- Moves `@types/react` and `@types/react-dom` to dependecies so that they will be installed with the prod env.
- Circle configuration
=> Added webpack prod config

src/components/Box/Box.story.tsx
=> Fixed Box story knob options

src/__snapshots__/index.test.ts.snap, src/components/PriceTag/PriceTag.story.tsx, src/components/PriceTag/PriceTag.style.tsx, src/components/PriceTag/PriceTag.template.tsx, src/components/PriceTag/PriceTag.test.tsx, src/components/PriceTag/__snapshots__/PriceTag.test.tsx.snap, src/themes/MosTheme/MosTheme.theme.ts
**Adds** ✨
- A `displayType` prop  `PriceTag`
=> Added displayType prop to PriceTag

.codeclimate.yml, src/__snapshots__/index.test.ts.snap, src/components/ButtonGroup/ButtonGroup.story.tsx, src/components/ButtonGroup/ButtonGroup.template.tsx, src/components/ButtonGroup/ButtonGroup.test.tsx, src/components/ButtonGroup/__snapshots__/ButtonGroup.test.tsx.snap, src/components/ButtonGroup/index.ts
resolves #47 
**Adds** ✨
- `ButtonGroup`
- CodeClimate config
=> Added ButtonGroup

src/index.ts
=> Added Popover export to index

src/__snapshots__/index.test.ts.snap, src/components/ButtonGroup/index.tsx, src/components/ButtonGroup/test.tsx, src/components/FoldOut/index.tsx, src/components/Link/index.tsx, src/components/Link/story.tsx, src/components/Link/style.tsx, src/components/Link/test.tsx, src/components/MessageStream/index.tsx, src/components/ScrollBox/test.tsx, src/index.ts, src/themes/MosTheme/MosTheme.theme.ts, src/types/ThemeType.ts
=> created Link component

src/__snapshots__/index.test.ts.snap, src/components/RadioButton/index.tsx, src/components/RadioButton/story.tsx, src/components/RadioButton/style.tsx, src/components/RadioButton/test.tsx, src/components/RadioButtonGroup/index.tsx, src/components/RadioButtonGroup/story.tsx, src/index.ts, src/themes/MosTheme/MosTheme.theme.ts, src/types/ThemeType.ts
**Adds** ✨
- RadioButton
- RadioButtonGroup
=> Radiobutton

src/components/Text/index.tsx, src/components/Text/story.tsx, src/components/Text/style.tsx, src/components/Text/test.tsx
**Adds** ✨
- Adds compact styling to `Text`
=> Added compact styling to Text

src/__snapshots__/index.test.ts.snap, src/components/Popover/__snapshots__/test.tsx.snap, src/components/Popover/index.tsx, src/components/Popover/story.tsx, src/components/Popover/style.tsx, src/components/Popover/test.tsx
**Changes** 🌀
- `Popover` positioning
=> Popoverfixes

src/__snapshots__/index.test.ts.snap, src/components/Box/__snapshots__/test.tsx.snap, src/components/Box/index.tsx, src/components/Box/style.tsx, src/components/Box/test.tsx
resolves #82 
**Changes** 🌀
- Boolean 'inline' added to Box component props to be able to switch between 'flex' and 'inline-flex'   display modes.
=> Avoid extra elements

src/__snapshots__/index.test.ts.snap, src/components/MessageStream/index.tsx
**Changes** 🌀
- Updates MessageStream to display formatted html in messages when a message contains html tags.
=> Messagestream update

package.json
**Adds** ✨
- `npm run build` to prepublish
=> Adds build to prepublish

src/__snapshots__/index.test.ts.snap, src/components/Button/index.tsx, src/components/Button/story.tsx, src/components/Button/style.tsx, src/components/Button/test.tsx, src/components/Modal/story.tsx, src/themes/MosTheme/MosTheme.theme.ts
**Adds** ✨
- Feature flat variant conform the codepen below:
https://codepen.io/Dreamdealer/pen/d4babc5b7f5b785b447fce53fd1d86d7?editors=1100
=> Buttonvariants

PULL_REQUEST_TEMPLATE.md
resolves #[resolved issue number]
**Adds** ✨
- Feature `foo`
**Changes** 🌀
- Feature `foo` to support `bar`
**Removes** 👋
- depracted `foop` method
proposed release: [`major`|`minor`|`patch`]
resolves #[resolved issue number]
**Adds** ✨
- Feature `foo`
**Changes** 🌀
- Feature `foo` to support `bar`
**Removes** 👋
- depracted `foop` method
- Feature `foo` no longer supports `foo` and needs to be converted to `foop`
=> Updated pr template

.gitignore, src/index.ts
**Adds** ✨
- Exposes the InlineNotification component
=> Added InlineNotification component

src/__snapshots__/index.test.ts.snap, src/components/Box/index.tsx, src/components/Box/story.tsx, src/components/Box/style.tsx, src/components/Box/test.tsx
resolves #119 
**Changes** 🌀
- Implements Box as a general layout component by adding the following props: 
`width` `padding` `maxWidth` `minWidth` `minHeight`
=> Box as a general layout component

src/__snapshots__/index.test.ts.snap, src/components/Box/style.tsx, src/components/Modal/__snapshots__/test.tsx.snap, src/components/Modal/index.tsx, src/components/Modal/story.tsx, src/components/Modal/style.tsx
**Adds** ✨
- Fixed width to the modal to allow for percentual styling inside of it.
=> Added fixed width to modal

src/__snapshots__/index.test.ts.snap, src/components/BreakpointProvider/index.tsx, src/components/Button/story.tsx, src/components/Contrast/story.tsx, src/components/EmptyState/index.tsx, src/components/ErrorBoundary/__snapshots__/test.tsx.snap, src/components/FoldOut/story.tsx, src/components/Icon/story.tsx, src/components/MessageStream/index.tsx, src/components/Modal/index.tsx, src/components/Notification/index.tsx, src/components/Popover/story.tsx, src/components/RadioButton/index.tsx, src/components/ScrollBox/story.tsx, src/components/Select/Option/index.tsx, src/components/Select/index.tsx, src/components/TextField/index.tsx, src/components/Toggle/index.tsx
**Removes** 👋
- Use of deprecated Spacers within components in favor of Box components
=> Replaced all Spacers with Boxes

src/__snapshots__/index.test.ts.snap, src/components/Spacer/story.tsx
proposed release: patch
**Adds** ✨
- Deprecated sign to Spacer component
=> Added deprecated icon to the spacer component

src/__snapshots__/index.test.ts.snap, src/components/Modal/style.tsx
**Changes** 🌀
- Lowered z-index of Modal so it doesn't clash with the z-index of elements that should be able to be rendered within the Modal such as the Select window.
=> Lowered Modal z-index

PULL_REQUEST_TEMPLATE.md, src/index.ts
new pr template ⤵️ 
proposed release: [`major`|`minor`|`patch`]
resolves #[resolved issue number]
**Adds** ✨
- Feature `foo`
**Changes** 🌀
- Feature `foo` to support `bar`
**Removes** 👋
- depracted `foop` method
- Feature `foo` no longer supports `foo` and needs to be converted to `foop`
=> Added components to index and changed PR template

src/__snapshots__/index.test.ts.snap, src/components/Button/index.tsx, src/components/Button/story.tsx, src/components/Button/style.tsx, src/components/Button/test.tsx
proposed release: patch
**Adds** ✨
- Button icon can now be defined with props.
=> button-icon

src/components/Modal/index.tsx, src/components/Modal/test.tsx
resolves #127 
**Changes** 🌀
- Modal to support close on click outside the modal body
=> Added close on click outside to Modal

src/__snapshots__/index.test.ts.snap, src/components/Popover/__snapshots__/test.tsx.snap, src/components/Popover/style.tsx, src/components/Skeleton/Text/index.tsx, src/components/Skeleton/Text/style.tsx, src/components/Skeleton/index.tsx, src/components/Skeleton/story.tsx, src/components/Skeleton/style.tsx, src/components/Skeleton/test.tsx, src/components/Table/story.tsx, src/index.test.ts, src/index.ts, src/themes/MosTheme/MosTheme.theme.ts, src/types/ThemeType.ts, src/utility/calculateRandomPercentage/index.ts, src/utility/calculateRandomPercentage/test.ts
**Adds** ✨
- A `Skeleton` component.
=> Added text skeleton

src/__snapshots__/index.test.ts.snap, src/components/Skeleton/Button/index.tsx, src/components/Skeleton/Button/style.tsx, src/components/Skeleton/index.tsx, src/components/Skeleton/story.tsx, src/components/Skeleton/style.tsx, src/components/Skeleton/test.tsx, src/themes/MosTheme/MosTheme.theme.ts, src/utility/calculateRandomPercentage/index.ts
proposed release: patch
**Adds** ✨
- Feature Skeleton now has a button variant
=> Skeleton button

src/__snapshots__/index.test.ts.snap, src/components/Select/story.tsx, src/components/Select/style.tsx
resolves #139 
**Changes** 🌀
- Padding and border based on open/closed state of `Select`
=> made Select window invisible when collapsed

config/webpack/webpack.config.js
resolves #81 
**Changes** 🌀
- Webpack config to export source-maps
=> Fixed source-maps

src/__snapshots__/index.test.ts.snap, src/components/TextField/index.tsx, src/components/TextField/story.tsx, src/components/TextField/style.tsx, src/components/TextField/test.tsx, src/themes/MosTheme/MosTheme.theme.ts
**Changes** 🌀
- Component `TextField` has new design and the label is removed.
- `label` is removed
- `changeHandler` is now `onChange`
=> Updated TextField

src/components/Modal/__snapshots__/story.storyshot, src/components/ScrollBox/__snapshots__/story.storyshot, src/components/ScrollBox/style.tsx, src/components/Select/__snapshots__/story.storyshot
resolves #112
**Changes** 🌀
- Added some styles to `ScrollBox` to make the scrollbar dynamic.
=> Dynamic scrollbar inside the ScrollBox

src/components/Spacer/__snapshots__/story.storyshot, src/components/Toaster/__snapshots__/story.storyshot, src/components/Toaster/index.tsx, src/components/Toaster/story.tsx, src/components/Toaster/style.tsx, src/components/Toaster/test.tsx, src/components/Toggle/__snapshots__/story.storyshot, src/components/TransitionAnimation/__snapshots__/story.storyshot, src/index.ts, src/themes/MosTheme/MosTheme.theme.ts, src/types/ThemeType.ts
**Adds** ✨
- Feature `Toaster component`
=> Toaster Component

src/components/Tile/__snapshots__/story.storyshot, src/components/Tile/index.tsx, src/components/Tile/story.tsx
**Changes** 🌀
- Removed padding from `Tile` component
=> removed padding from Tile

src/components/Table/__snapshots__/story.storyshot, src/components/Table/style.tsx
**Changes** 🌀
- Removed last bottom-border from table rows
=> removed last bottom-border from table rows

config/jest/__mocks__/reactPopper.tsx, src/components/Modal/story.tsx, src/components/MultiButton/Option/index.tsx, src/components/MultiButton/Option/style.tsx, src/components/MultiButton/__snapshots__/story.storyshot, src/components/MultiButton/index.tsx, src/components/MultiButton/story.tsx, src/components/MultiButton/style.tsx, src/components/MultiButton/test.tsx, src/components/Popover/__snapshots__/story.storyshot, src/components/Popover/__snapshots__/test.tsx.snap, src/components/PriceTag/__snapshots__/story.storyshot, src/components/RadioButtonGroup/__snapshots__/story.storyshot, src/components/Raised/__snapshots__/story.storyshot, src/components/ScrollBox/__snapshots__/story.storyshot, src/components/Select/__snapshots__/story.storyshot, src/components/Skeleton/__snapshots__/story.storyshot, src/components/Spacer/__snapshots__/story.storyshot, src/components/Table/__snapshots__/story.storyshot, src/components/Tile/__snapshots__/story.storyshot, src/components/Toaster/__snapshots__/story.storyshot, src/components/Toggle/__snapshots__/story.storyshot, src/components/TransitionAnimation/__snapshots__/story.storyshot, src/index.ts, src/themes/MosTheme/MosTheme.theme.ts, src/types/ThemeType.ts
**Adds** ✨
- `MultiButton` component
=> MultiButton

src/components/FormRow/__snapshots__/story.storyshot, src/components/TextField/formatters/withCurrencyFormatting/__snapshots__/story.storyshot, src/components/TextField/style.tsx, src/themes/MosTheme/MosTheme.theme.ts
**Adds** ✨
- added white background to `Textfield`
=> added white background to textfield

config/jest/__mocks__/cssMock.js, config/jest/__mocks__/simplebarCss.ts, config/jest/jest.config.json, config/storybook/webpack.config.js, config/typescript/tsconfig.json, config/webpack/webpack.config.js, package-lock.json, package.json, src/components/Modal/__snapshots__/story.storyshot, src/components/MultiButton/__snapshots__/story.storyshot, src/components/Popover/__snapshots__/story.storyshot, src/components/PriceTag/__snapshots__/story.storyshot, src/components/RadioButtonGroup/__snapshots__/story.storyshot, src/components/Raised/__snapshots__/story.storyshot, src/components/ScrollBox/__snapshots__/story.storyshot, src/components/ScrollBox/index.tsx, src/components/ScrollBox/style.tsx, src/components/Select/__snapshots__/story.storyshot, src/components/Skeleton/__snapshots__/story.storyshot, src/components/Spacer/__snapshots__/story.storyshot, src/components/Table/__snapshots__/story.storyshot, src/components/Tile/__snapshots__/story.storyshot, src/components/Toaster/__snapshots__/story.storyshot, src/components/Toggle/__snapshots__/story.storyshot, src/components/TransitionAnimation/__snapshots__/story.storyshot
resolves #181 
**Adds** ✨
- SSR compatibility 🎉 
- ExtractTextPlugin to webpack
- babel-loader to build config
**Changes** 🌀
- simplebar version to v3
=> SSR compatibility

src/components/Modal/__snapshots__/story.storyshot, src/components/Modal/index.tsx, src/components/Modal/story.tsx, src/components/Modal/test.tsx
proposed release:`patch`
resolves #188 
**Adds** ✨
- A story that shows this case
**Changes** 🌀
- Removes the close button to withhold closing untill a condition is met.
=> Removed close button without closeAction

src/components/Select/__snapshots__/story.storyshot, src/components/Select/index.tsx, src/components/Select/story.tsx, src/components/Select/style.tsx, src/components/Select/test.tsx, src/components/Skeleton/__snapshots__/story.storyshot, src/components/Spacer/__snapshots__/story.storyshot, src/components/Table/__snapshots__/story.storyshot, src/components/Tile/__snapshots__/story.storyshot, src/components/Toaster/__snapshots__/story.storyshot, src/components/Toggle/__snapshots__/story.storyshot, src/components/TransitionAnimation/__snapshots__/story.storyshot, src/themes/MosTheme/MosTheme.theme.ts
**Adds** ✨
- a `disabled` state to the Select Component
=> added disabled state to Select Component

config/jest/setup.tsx, src/components/Checkbox/__snapshots__/story.storyshot, src/components/Checkbox/index.tsx, src/components/Checkbox/test.tsx, src/components/Table/Header/test.tsx, src/components/Table/Row/index.tsx, src/components/Table/Row/test.tsx, src/components/Table/__snapshots__/story.storyshot, src/components/Table/index.tsx, src/components/Table/story.tsx, src/components/Table/test.tsx, src/declarations/global.d.ts, src/utility/SubscriptionContext/index.tsx
resolves #169
**Adds** ✨
- `shift-select` option to bulk toggle the Checkboxes.
=> Added bulk actions to Table

src/components/Box/__snapshots__/story.storyshot, src/components/Box/index.tsx, src/components/Box/story.tsx, src/components/Box/style.tsx, src/components/Button/__snapshots__/story.storyshot, src/components/ButtonGroup/__snapshots__/story.storyshot, src/components/Checkbox/__snapshots__/story.storyshot, src/components/Contrast/__snapshots__/story.storyshot, src/components/EmptyState/__snapshots__/story.storyshot, src/components/FoldOut/__snapshots__/story.storyshot, src/components/FormRow/__snapshots__/story.storyshot, src/components/Icon/__snapshots__/story.storyshot, src/components/InlineNotification/__snapshots__/story.storyshot, src/components/MessageStream/__snapshots__/story.storyshot, src/components/Modal/__snapshots__/story.storyshot, src/components/MultiButton/__snapshots__/story.storyshot, src/components/Notification/__snapshots__/story.storyshot, src/components/Popover/__snapshots__/story.storyshot, src/components/RadioButton/__snapshots__/story.storyshot, src/components/RadioButtonGroup/__snapshots__/story.storyshot, src/components/Raised/__snapshots__/story.storyshot, src/components/ScrollBox/__snapshots__/story.storyshot, src/components/Select/__snapshots__/story.storyshot, src/components/Table/__snapshots__/story.storyshot, src/components/TextField/formatters/withCurrencyFormatting/__snapshots__/story.storyshot, src/components/Tile/__snapshots__/story.storyshot, src/components/Toaster/__snapshots__/story.storyshot, src/components/Toggle/__snapshots__/story.storyshot, src/components/TransitionAnimation/__snapshots__/story.storyshot
**Adds** ✨
- `position` prop to Box Component
- `top` prop to Box Component
- `right` prop to Box Component
- `bottom` prop to Box Component
- `left` prop to Box Component
=> Added props to Box component

src/components/Badge/test.tsx
Adds unit-tests to the `Badge` component so there is 100% test-coverage for this component.
**Adds** ✨
- Unit-tets to `Badge` component.
=> Added unit-tests for Badge component

src/components/Checkbox/index.tsx, src/components/Table/Header/index.tsx, src/components/Table/Header/test.tsx, src/components/Table/Row/index.tsx, src/components/Table/Row/test.tsx, src/components/Table/index.tsx, src/components/Table/story.tsx, src/components/Table/test.tsx
**Adds** ✨
- Checks can now be set with props
**Changes** 🌀
- Component no longer uses `utility/SubscriptionContext `
**Removes** 👋
- utility/SubscriptionContext functionality.
**Breaking** 🔥
- onSelection callback now provides different data and passes you an update rows to directly be used with any state.
=> Table check

src/components/Button/__snapshots__/story.storyshot, src/components/Button/style.tsx, src/components/ButtonGroup/__snapshots__/story.storyshot, src/components/Contrast/__snapshots__/story.storyshot, src/components/EmptyState/__snapshots__/story.storyshot, src/components/FoldOut/__snapshots__/story.storyshot, src/components/MessageStream/__snapshots__/story.storyshot, src/components/Modal/__snapshots__/story.storyshot, src/components/MultiButton/__snapshots__/story.storyshot, src/components/Popover/__snapshots__/story.storyshot, src/components/Select/__snapshots__/story.storyshot, src/components/Table/__snapshots__/story.storyshot, src/components/Toaster/__snapshots__/story.storyshot, src/components/TransitionAnimation/__snapshots__/story.storyshot, src/components/TransitionAnimation/__snapshots__/test.tsx.snap, src/components/TransitionAnimation/animations/slide.ts, src/components/TransitionAnimation/animations/slideDown.ts, src/components/TransitionAnimation/animations/slideLeft.ts, src/components/TransitionAnimation/animations/slideRight.ts, src/components/TransitionAnimation/animations/slideUp.ts, src/components/TransitionAnimation/story.tsx, src/components/TransitionAnimation/style.tsx, src/components/TransitionAnimation/test.tsx
Adds a new transition: `slide` which animates down from above 
**Adds** ✨
- `slide` animation
**Other changes** 🌀
- button no longer has a scale animation on hover
- removed unused css rules
=> Slide in animation

.github/PULL_REQUEST_TEMPLATE.md
Adds a checkbox to the PR template to indicate that that there has been approval from a designer on any visual and behavioral changes in a component.
=> Added design approval checkbox to PR template

src/components/FormRow/__snapshots__/story.storyshot, src/components/Range/__snapshots__/story.storyshot, src/components/TextField/__snapshots__/story.storyshot, src/components/TextField/index.tsx, src/components/TextField/story.tsx, src/components/TextField/style.tsx, src/themes/MosTheme/MosTheme.theme.ts
resolves #241 and #242
**Changes** 🌀
- disabled knob added to `Textfield.numberFormatting`
- adjusted styling
=> Textfield style bugs

src/components/Toaster/__snapshots__/story.storyshot, src/components/Toaster/index.tsx, src/components/Toaster/story.tsx, src/components/Toaster/test.tsx
resolves #259
**Adds** ✨
- Auto dismiss prop
=> Added auto dismiss prop to Toaster

src/components/Checkbox/__snapshots__/story.storyshot, src/components/Checkbox/index.tsx, src/components/FormRow/__snapshots__/story.storyshot, src/components/FormRow/index.tsx, src/components/FormRow/story.tsx, src/components/FormRow/style.tsx
resolves #272 
**Changes** 🌀
- Implements Separated component in FormRow
**Removes** 👋
- Depracted `.checkbox` class in FormRow and therefore it's css
**Breaking** 🔥
- Removed .checkbox classname and styling
=> Removed checkbox class

src/components/Separated/__snapshots__/story.storyshot, src/components/Spacer/__snapshots__/story.storyshot, src/components/Spinner/__snapshots__/story.storyshot, src/components/Spinner/index.tsx, src/components/Spinner/story.tsx, src/components/Spinner/style.tsx, src/components/Table/__snapshots__/story.storyshot, src/components/TextArea/__snapshots__/story.storyshot, src/components/Tile/__snapshots__/story.storyshot, src/components/Toaster/__snapshots__/story.storyshot, src/components/TransitionAnimation/__snapshots__/story.storyshot, src/index.ts
resolves #269
**Adds** ✨
- Spinner component
=> Created spinner component

CONTRIBUTING.md, README.md
Adds documentation on coding conventions. 
=> Added code conventions documentation

src/components/Popover/test.tsx, src/components/RadioButton/style.tsx, src/components/ScrollBox/test.tsx, src/components/TextField/formatters/withNumberFormatting/index.tsx, src/components/TextField/story.tsx, src/utility/rgba/index.ts, tsconfig.json, tslint.json
- Added no-unused flag to typscript
=> Added no-unused flag to typscript

package.json
resolves #333 
- Changes output dir from `dist` to `lib` and thus it doth fix the build
=> Fixed 1.x build

src/components/Breadcrumbs/index.tsx, src/components/Modal/index.tsx, src/components/Popover/index.tsx, src/components/RadioButton/index.tsx, src/components/Range/index.tsx, src/components/Select/Option/index.tsx, src/components/Select/index.tsx, src/components/Table/Cell/index.tsx, src/components/Table/CompactHeaders/index.tsx, src/components/Table/Row/index.tsx, src/components/Table/TableHeaders/index.tsx, src/components/Table/index.tsx, src/components/Toast/index.tsx
Relates to #11 
- Adds ARIA labels according to https://www.w3.org/TR/wai-aria-practices where necessary.
- Adds functionality to close `Modal`/`Popover` with escape key
=> Added ARIA labels

.circleci/config.yml, package-lock.json, package.json
Adds bundlesize to give us better insights in the actual cost of certain changes. No threshold has been seen till further research
- None
- None
- Added bundlesize
=> Bundlesize

.circleci/config.yml, package.json
Deploys Storybook to GitHub pages when released
=> Added storybook-to-ghpages to CI

src/components/Toaster/index.tsx, src/components/Toaster/test.tsx
Fixes issue with `window is not defined` errors in SSR envs.
- None
- None
- Removes window check with console error.
=> Removed window check

.circleci/config.yml
Hopefully fixes ghPages deployer
=> Add GitHub to CircleCI known_hosts

src/components/Box/style.tsx
- Fixed breaking Box when extended.
=> Moved ; into style rules for box

src/index.ts
Adds the gentheme function to `index.ts`
- Adds the gentheme function to `index.ts`
=> added gentheme to index.ts exports

.huskyrc, package.json, src/components/Link/index.tsx, yarn.lock
- Added commit hooks to pre-push and post-checkout.
=> Commit hooks

src/components/Box/index.tsx, src/components/Slider/index.tsx, src/components/Slider/story.tsx, src/components/Slider/style.tsx, src/components/Slider/test.tsx, src/index.ts, src/themes/ExperimentalCustomTheme/genTheme.ts, src/themes/MosTheme/MosTheme.theme.ts, src/types/ThemeType/index.ts
Creates a `Slider` component.
This is a component similar to the `Range` component but it only has one value.
This component is required for the https://myonlinestore.atlassian.net/browse/STRF-146 ticket
- The new component `Slider` has been added.
- Component `Box` has a new `alignItems` value: `baseline`
- Fixed minor typo in range css
=> Slider component

src/components/Select/index.tsx, src/components/Select/story.tsx, src/components/Select/style.tsx, src/components/Select/test.tsx, src/components/Table/test.tsx, yarn.lock
Fixes the behavior of the `Select` window. It now updates on scroll 🌈 .
- `Select` window position is now updated on scroll events. For now these are throttled by `window.requestAnimationFrame()` as suggested in https://developer.mozilla.org/en-US/docs/Web/API/Document/scroll_event . I actually tried using `throttle-debounce` but the throttle delay needed to be so short for it to look smooth that the performance gains over requestAnimationFrame seemed negligible.
=> Select fix scroll

.github/PULL_REQUEST_TEMPLATE.md
Adds a new checkbox to the checklist about documentation:
- Component `Foo` has been removed.
- Component `Bar` no longer supports prop `x`, you should use prop `y` from now on.
- Component `FooBar` has been redesigned.
- Component `Foo` now also supports an optional `size` props to increase it's size.
- The new component `Bar` has been added.
- Component `Foo` now uses the correct icon.
- Refactored some components.
=> Added documentation checkbox

src/components/Popover/index.tsx
While trying to fix a Popover bug i wrote some documentation for it.
Turns out it was an implementation error rather than a bug in Popover.
It would be a shame to discard the docs, right? 
- Popover documentation
=> Popover documentation

src/components/_MosCorporateTheme/story.tsx, src/index.ts, src/themes/MosCorporateTheme/index.tsx, src/themes/MosCorporateTheme/theme.ts
Resolves [GRWTH-736](https://myonlinestore.atlassian.net/browse/GRWTH-736)
Adds a theme for use of corporate style elements (only round buttons for now).
- none
- Adds `MosCorporateTheme`
- none
=> GRWTH-736 MosCorporateTheme

src/components/Select/index.tsx, src/components/Select/story.tsx, src/components/Select/style.tsx, src/components/Select/test.tsx, src/components/Table/test.tsx
Reverts MyOnlineStore/bricks#400
=> Revert "Select fix scroll"

src/components/Button/base/index.tsx, src/components/Button/base/style.tsx, src/components/Button/base/test.tsx, src/components/Button/index.tsx, src/components/Button/story.tsx, src/components/Button/test.tsx, src/components/ButtonGroup/story.tsx, src/components/IconButton/story.tsx, src/components/Link/story.tsx, src/components/MultiButton/story.tsx, src/components/TextualButton/index.tsx, src/components/TextualButton/story.tsx, src/components/TextualButton/test.tsx, src/components/_MerchantTheme/sampleContent.tsx, src/index.ts, src/themes/ExperimentalCustomTheme/genTheme.ts, src/themes/MosTheme/MosTheme.theme.ts, src/types/ThemeType/index.ts
resolves #412 
- None
- The new component `TextualButton` has been added.
- Moved tests for shared behaviour out of the `Button` test suite and moved them into a test suite for the button base.
=> Added implementation from TextualButton

README_TEMPLATE.mdx, docs/.babelrc, docs/package.json, docs/pages/_document.tsx, docs/yarn.lock, src/components/Badge/readme.mdx
- Added fixed styled-components ssr rendering for docs website
- Added a readme template to be used for components.
=> Added readme-template for components

src/components/Table/Card/index.tsx, src/components/Table/Cell/index.tsx, src/components/Table/Row/index.tsx, tslint.json
- Remove `no-unbound-method` rule from TSLint
=> Disable TSLint no-unbound-method

src/assets/README.md, src/assets/index.ts
=> Icon name docs

src/components/NativeSelect/index.tsx, src/components/NativeSelect/story.tsx, src/components/NativeSelect/style.tsx, src/components/NativeSelect/test.tsx, src/components/TextField/style.tsx, src/index.ts, src/themes/ExperimentalCustomTheme/genTheme.ts, src/themes/MosTheme/MosTheme.theme.ts, src/types/ThemeType/index.ts
https://myonlinestore.atlassian.net/browse/STRF-187
- None
- New component "native select" which is a styled native select with native options and functionality
=> New native select component added

src/components/Carousel/story.tsx, src/components/Progress/index.tsx, src/components/Progress/story.tsx, src/components/Progress/style.tsx, src/components/Progress/test.tsx, src/components/_MerchantTheme/sampleContent.tsx, src/index.ts, src/themes/ExperimentalCustomTheme/genTheme.ts, src/themes/MosTheme/MosTheme.theme.ts, src/types/ThemeType/index.ts
resolves #428 
- None
- The new component `Progress` has been added.
- None
=> Added Progress component

src/components/Progress/style.tsx
Changes the color used in Progress component to the correct color
- None
- None
- Changed used color from `primary.darker1` to `primary.base`
=> Changed progress component base color

src/components/Button/base/index.tsx, src/components/Button/base/style.tsx, yarn.lock
removes the `loading` prop on the button base DOM element. The passing of this prop to the dom element is unnecessary and causes warnings in the latest `styled-components` version:
```
Warning: Received `false` for a non-boolean attribute `loading`.
If you want to write it to the DOM, pass a string instead: loading="false" or loading={value.toString()}.
```
- none
- none
- Removed `loading` prop to button base DOM element
=> Renamed loading prop on button base element

src/components/Modal/index.tsx, src/components/Modal/test.tsx
=> Added testids to modal

.circleci/config.yml
Resolves https://myonlinestore.atlassian.net/browse/CASH-887 🤞
- CircleCI config
=> Adjusted CircleCI config

package.json
is another attempt at https://myonlinestore.atlassian.net/browse/CASH-887
=> Changed package.json repository url

src/assets/icons/copy.svg
=> Replaced copy icon

.github/workflows/deploy.yml
Moves the token to the checkout step
=> Moved token in deploy action

.github/workflows/deploy.yml
Reverts MyOnlineStore/bricks#479
=> Revert "Moved token in deploy action"

docs/components/ColorBoard.tsx, docs/markdown/design/colors.mdx
Add brand colors to design system
=> Add brand colors

packages/assets/package.json, packages/assets/scripts/types.js
Comparable to #506 , but for illustrations.
- Added correct svg types to illustration
=> Added correct svg types to illustration

packages/components/src/components/Checkbox/story.tsx, packages/components/src/components/Checkbox/style.tsx, packages/components/src/components/Checkbox/test.tsx, packages/components/src/components/RadioButton/index.tsx, packages/components/src/components/RadioButton/story.tsx, packages/components/src/components/RadioButton/style.tsx, packages/components/src/components/RadioButton/test.tsx, packages/components/src/components/Range/style.tsx, packages/components/src/components/Slider/style.tsx, packages/components/src/components/Toggle/index.tsx, packages/components/src/components/Toggle/story.tsx, packages/components/src/components/Toggle/style.tsx, packages/components/src/components/Toggle/test.tsx, packages/components/src/themes/MosTheme/MosTheme.theme.ts
- ThemeTypes for `CheckBox`, `RadioButton`, `Toggle`, `Slider` and `Range`
- Freshly styled Form Elements 🌈 
- All styles for the relevant components have been altered/tweaked
=> feat: implement 3.0 Form Element design

packages/components/src/components/InlineNotification/index.tsx, packages/components/src/components/NativeSelect/index.tsx, packages/components/src/components/NativeSelect/style.tsx, packages/components/src/components/Select/Option/index.tsx, packages/components/src/components/Select/Option/style.tsx, packages/components/src/components/Select/index.tsx, packages/components/src/components/Select/story.tsx, packages/components/src/components/Select/style.tsx, packages/components/src/components/Select/test.tsx, packages/components/src/components/TextArea/index.tsx, packages/components/src/components/TextArea/story.tsx, packages/components/src/components/TextArea/style.tsx, packages/components/src/components/TextField/index.tsx, packages/components/src/components/TextField/story.tsx, packages/components/src/components/TextField/style.tsx, packages/components/src/themes/MosTheme/MosTheme.theme.ts
- ThemeTypes for `NativeSelect`, `Select`, `TextArea` and `TextField`
- Freshly styled Form Fields 🌈
- All styles for the relevant components have been altered/tweaked
- Refactored Select a bit
=> feat: implement 3.0 Form fields design

packages/assets/src/icons/partial-checkmark.svg
Adds partial checkmark icon to bricks-assets.
- Partial checkmark icon
=> feat: Add partial checkmark icon

packages/components/src/components/Toggle/index.tsx, packages/components/src/components/Toggle/story.tsx
- removes `unavailable` props
- none
- none
=> feat(Toggle): removed unavailable prop

packages/components/src/components/Button/base/style.tsx, packages/components/src/components/IconButton/index.tsx
Adds explicit styling to button states to guarantee it's appearance in hostile environments.
- nope
- nuh ah
- explicit styling for IconButton
=> fix(IconButton): explicit styling to prevent cascading properties

packages/components/src/components/Notification/index.tsx, packages/components/src/components/Notification/style.tsx, packages/components/src/themes/MosTheme/MosTheme.theme.ts
adds the new Notification styling 🎨
- Notification theme object
- none
- none
=> feat(Notification): new Notification styling

packages/components/docs/containers/examples/badges/CounterExamples.tsx, packages/components/docs/containers/examples/badges/SubscriptionBadgesExamples.tsx, packages/components/docs/lib/componentMap.tsx, packages/components/docs/markdown/components/badges.mdx, packages/components/docs/package.json, packages/components/docs/pages/index.tsx, packages/components/docs/yarn.lock
Some fixes for the design system site that were necessary due to the breaking changes in bricks 3.
=> fix: implement bricks 3 changes in design system site

packages/components/src/components/Link/style.tsx, packages/components/src/components/TextualButton/index.tsx
- More override prevention 🙄  
=> fix(Link, TextualButton): Prevent unwanted focus overrides

packages/components/src/components/Select/index.tsx
- Refactored Select component to hooks
=> refactor(Select): Refactored Select component to hooks

packages/components/src/components/Accordion/index.tsx, packages/components/src/components/Accordion/story.tsx, packages/components/src/components/Accordion/style.tsx, packages/components/src/components/Accordion/test.tsx, packages/components/src/index.ts, packages/components/src/themes/CustomTheme/genTheme.ts, packages/components/src/themes/MosTheme/MosTheme.theme.ts, packages/components/src/types/ThemeType/index.ts
- none
- `Accordion` component
- none
=> feat(Accordion): Added Accordion component

.gitignore, packages/components/src/components/Card/index.tsx, packages/components/src/components/Card/story.tsx, packages/components/src/components/Card/style.tsx, packages/components/src/index.ts, packages/components/src/themes/CustomTheme/genTheme.ts, packages/components/src/themes/MosTheme/MosTheme.theme.ts, packages/components/src/types/ThemeType/index.ts
- none
- Added Card component
- none
=> feat(Card): Added new Card component

.github/workflows/pr-title.yml
Adds a PR Title action in favor of the GitHub pr title app
=> chore: Added PR Title action

.huskyrc, .huskyrc.js, commitlint.config.js, package.json, yarn.lock
Adds commitlint for linting commits
=> chore: Added commitlint

packages/assets/src/icons/save.svg
Adds save icon to assets
- Adds a save icon
=> feat(Assets): Add save icon

packages/assets/src/icons/bus.svg
=> feat(Assets): Add BusIcon

packages/assets/src/icons/comment-empty.svg
=> feat: Added CommentEmptyIcon

packages/components/src/components/PromotionBadge/index.tsx
- None
- PromotionBadge is now always rendered as uppercase
- None
<details>
_Tip: make sure the first commit …
=> feat(PromotionBadge): Made text uppercase

packages/components/package.json
- None
- Added support for package sb composition
- None
<details>
_Tip: make sure the first commit message is …
=> chore: Storybook update

packages/components/.storybook/preview.js, packages/components/src/__fixtures__/themeDecorator.tsx, packages/components/src/components/CurrencyField/story.tsx, packages/components/src/components/IconButton/index.tsx, packages/components/src/components/NumberField/index.tsx, packages/components/src/components/NumberField/story.tsx, packages/components/src/components/TextField/index.tsx, packages/components/src/components/TextField/story.tsx, packages/components/src/components/TextField/style.tsx, packages/components/src/components/TextField/test.tsx, packages/components/src/themes/MosTheme/MosTheme.theme.ts
- None
- Added `subdued` variant to IconButton
- Added `icon` prop to `TextField`
- Refactored several components and stories to hooks and SFC
- Added a themes toolbar with several example themes
<details>
More info …
=> feat: Added icon to Textfield

packages/components/src/components/Card/index.tsx
- Added testid to `Card`
<details>
</details>
=> fix(Card): Added testid prop

packages/components/src/components/FoldOut/style.tsx
https://myonlinestore.atlassian.net/browse/MWW-8289
- none
- none
- create linear-gradient with RGBA values instead of transparent keyword.
<details> …
=> fix(FoldOut): Converted linear-gradient to use RGBA values

packages/components/src/components/Link/style.tsx
- Fixed incorrect button styling in Link component
<details>
_Tip: make sure the first commit message is the one you want to merge, because that's the one Github picks …
=> fix(Link): Fixed Link button hover styles

packages/components/src/components/Table/Row/index.tsx, packages/components/src/components/Table/Row/style.tsx, packages/components/src/components/Table/index.tsx, packages/components/src/components/Table/story.tsx, packages/components/src/components/Table/style.tsx, packages/components/src/themes/MosTheme/MosTheme.theme.ts
- Adds error state to the Table Row, this changes the ThemeType.
<details>
_Tip: make sure the first commit message is the one you want to merge, because that's the one Github …
=> feat!: Table row error state

packages/components/src/components/Pagination/index.tsx, packages/components/src/components/Pagination/story.tsx, packages/components/src/components/Pagination/style.tsx, packages/components/src/components/Pagination/test.tsx, packages/components/src/index.ts, packages/components/src/themes/CustomTheme/genTheme.ts, packages/components/src/themes/MosTheme/MosTheme.theme.ts, packages/components/src/types/ThemeType/index.ts
Adds Pagination 1️⃣2️⃣3️⃣...🔟
- `Pagination` added to theme object
- `Pagination` component
<details>
_Tip: make sure the first commit message …
=> feat!: Added Pagination component

packages/components/src/components/FileInput/index.tsx, packages/components/src/components/FileInput/story.tsx
- Adds error messages and filetype filtering
<details> …
=> chore: Adds error messages and filetype filtering

packages/components/src/components/Toolbar/index.tsx, packages/components/src/components/Toolbar/story.tsx
- None
- Added Toolbar component
- None
<details>
_Tip: make sure the first commit message is the one you want …
=> feat: Added Toolbar component

packages/components/src/components/FileInput/index.tsx, packages/components/src/components/FileInput/story.tsx, packages/components/src/components/FileInput/style.tsx, packages/components/src/themes/MosTheme/MosTheme.theme.ts
Please ignore the actual toolbar. This is going to be replaced with the new separate component @CarloPalinckx created just now.
=> chore: Added Toolbar to FileInput Component

packages/components/src/components/FormRow/index.tsx, packages/components/src/components/FormRow/story.tsx, packages/components/src/components/NativeSelect/story.tsx
...adjusts the form row margins to match the figma designs.
- Adjusted margins in `FormRow`
<details>
_Tip: make sure the first commit message is the one you want to …
=> fix(FormRow): Adjusted FormRow margins

packages/components/src/components/TextualButton/index.tsx
- None
- None
- The icon in the TextualButton was missaligned
<details>
_Tip: make sure the first commit …
=> fix: Aligned icon correctly on TextualButton

packages/components/src/index.ts
- Adds Toolbar to exports
<details>
</details>
=> fix(Toolbar): Added Toolbar as export

packages/components/src/components/FileInput/index.tsx, packages/components/src/components/FileInput/story.tsx, packages/components/src/components/FileInput/style.tsx, packages/components/src/themes/MosTheme/MosTheme.theme.ts
- Fixed hover/drop/focus states according to latest design
<details>
_Tip: make sure the first commit message is the one you want to merge, because that's the one Github …
=> chore: Fixed hover/drop/focus states

packages/components/src/components/Button/base/style.tsx, packages/components/src/components/Tag/index.tsx, packages/components/src/components/Tag/story.tsx, packages/components/src/components/Tag/test.tsx, packages/components/src/index.ts, packages/components/src/themes/CustomTheme/genTheme.ts, packages/components/src/themes/MosTheme/MosTheme.theme.ts, packages/components/src/types/ThemeType/index.ts
- Added `Tag` component with adjusted ThemeType
<details> …
=> feat(Tag): Added Tag component

packages/components/src/components/ColorField/index.tsx, packages/components/src/components/ColorField/story.tsx, packages/components/src/components/CurrencyField/index.tsx, packages/components/src/components/CurrencyField/story.tsx, packages/components/src/index.ts
- Added new ColorField component
<details> …
=> feat: Added new ColorField component

packages/components/src/components/ColorField/index.tsx, packages/components/src/components/ColorField/test.tsx
=> chore: Added tests to ColorInput component

packages/components/docs/yarn.lock
- Fixed docs lockfile
<details>
</details>
=> fix: Fixed docs lockfile

packages/components/src/components/FormRow/index.tsx
- Fixed basis bug formrow
<details>
</details>
=> fix: Fixed basis bug formrow

packages/components/src/components/FormRow/index.tsx
- Added width to formrow
<details>
</details>
=> fix: Added width to formrow

packages/components/src/components/ImageRadio/index.tsx, packages/components/src/components/ImageRadio/test.tsx
- Adds tests to new ImageRadio component
<details> …
=> chore: Added tests to ImageRadio

packages/components/src/components/Button/base/index.tsx, packages/components/src/components/Button/index.tsx, packages/components/src/components/Heading/index.tsx, packages/components/src/components/IconButton/index.tsx, packages/components/src/components/Text/index.tsx, packages/components/src/components/TextualButton/index.tsx
- None
- Added box props to several components
- None
<details>
_Tip: make sure the first commit message is …
=> feat: Added box props to several components
