MyOnlineStore/bricks

.travis.yml
package.json
src/__snapshots__/index.test.ts.snap
src/components/Spacer/Spacer.style.tsx
src/index.d.ts

This PR:
- changes the default `display` value of `Spacer` to `block`.
- changes `codestyle-check` and `codestyle-fix` to `cs-check` and `cs-fix`

Changed Spacer default display to block

---

package.json
src/utility/styled/styled.ts

Removes the `--force` flag so that CI rejects builds on cs errors.

Removed --force flag

---

package-lock.json
package.json
src/__snapshots__/index.test.ts.snap
src/components/FoldOut/FoldOut.story.tsx
src/components/FoldOut/FoldOut.style.tsx
src/components/FoldOut/FoldOut.template.tsx
src/components/FoldOut/FoldOut.test.tsx
src/components/FoldOut/__snapshots__/FoldOut.test.tsx.snap

**Resolves** #27 
**Adds** ✨
- `resize-observer-polyfill` dependency.
**Changes** 🌀
- Implementation of `ResizeObserver` for update on inner height regardless of window resize.
**Removes** 👋
- window `resize` event listener.

Added Foldout resizing on inner resize

---

PULL_REQUEST_TEMPLATE.md
config/jest/jest.config.json
src/__snapshots__/index.test.ts.snap
src/components/FoldOut/FoldOut.story.tsx
src/components/Icon/Icon.story.tsx
src/components/Notification/Notification.template.tsx
src/components/Spacer/Spacer.story.tsx
src/components/Spacer/Spacer.style.tsx
src/components/Spacer/Spacer.template.tsx
src/index.ts
src/utility/trbl/index.ts
src/utility/trbl/trbl.test.ts

resolves #48 
**Adds** ✨
- `trbl` util that helps with building 4-points coordinates of (css-like) shorthands.
**Changes** 🌀
- `Spacer` to support `trbl`
- The `resolves` line in the PR-template so it actually closes issues.

Added trbl utility

---

src/__snapshots__/index.test.ts.snap
src/components/Link/style.tsx

**Changes** 🌀
- `Link` now has a transparent background on its hover state to provide a more consistent styling.

Added transparent background color to Link hover state

---

config/webpack/webpack.config.js
src/components/Icon/assets/close.svg

resolves #109 
**Adds** ✨
- Removal of 'title', 'desc', 'defs', 'style' tags when loading svg's in webpack config
**Changes** 🌀
- Updated medium sized close icon to fill-based version

replaced close icon and updated webpack config to remove tags from svgs

---

src/components/Popover/index.tsx
src/components/Popover/story.tsx
src/components/Popover/test.tsx

resolves #116 
**Changes** 🌀
- Popover offset can now be set for both the horizontal and the vertical axes, instead of only for the vertical axis. This is implemented using `offset` and `distance` props. Distance specifies the distance between toggle and popover while offset specifies the offset of the popover body relative to the popover arrow.

Popover offset on both axes

---

src/__snapshots__/index.test.ts.snap
src/components/Heading/index.tsx

**Changes** 🌀
- Changes default textAlign on Heading to `''` so it assumes alignment from its parent.

changed default textAlign on Header

---

src/__snapshots__/index.test.ts.snap
src/components/Skeleton/Button/style.tsx
src/components/Skeleton/Text/style.tsx
src/components/Skeleton/style.tsx

**Changes** 🌀
- Moves `user-select: none` to skeleton base style.
- the skeletons theme font-size is now used as font-size instead of height to make it consistent even when box-sizing border-box is set.

Fixed button skeleton height

---

config/webpack/webpack.config.js
package-lock.json

fixes warnings about minified development code when using this package. You can test it by using it in CRA and `npm link` it.
proposed release: patch
**Adds** ✨
- DefinePlugin to webpack config to set `NODE_ENV` to `production`. This fixes warnings about minified development code.
**Changes** 🌀
- Updated packages thru `npm audit`

Added production NODE_ENV to webpack config, updated packages

---

src/__snapshots__/index.test.ts.snap
src/components/Modal/index.tsx
src/components/Modal/story.tsx
src/components/Modal/style.tsx
src/components/Modal/test.tsx

**Adds** ✨
- A `size` prop to the `Modal` with the options `small` and `large`

Added modal size prop

---

src/__snapshots__/index.test.ts.snap
src/components/InlineNotification/index.tsx
src/components/InlineNotification/story.tsx

**Adds** ✨
- makes the message prop optional and provides an option to render components inside it as children.

Added inline-notification children

---

src/__snapshots__/index.test.ts.snap
src/themes/MosTheme/MosTheme.theme.ts

**Changes** 🌀
- Changed the color of  the `info` severity from: `lighter2` to: `lighter3`

Changed info color from lighter2 to lighter3.

---

src/__snapshots__/index.test.ts.snap
src/components/ErrorBoundary/__snapshots__/test.tsx.snap
src/components/Notification/index.tsx

resolves #143 
**Changes** 🌀
- When notification contains a multiline text-message, the icon now aligns on the first text line and the text lines are indented on every line.

Fixed Notification Icon bug

---

src/components/Toggle/__snapshots__/story.storyshot
src/components/Toggle/index.tsx
src/components/Toggle/story.tsx
src/components/Toggle/style.tsx
src/components/Toggle/test.tsx
src/themes/MosTheme/MosTheme.theme.ts

**Changes** 🌀
- Label for `Toggle` is now optional.
- `Toggle` to actually display the toggle label when set.
- Added optional `disabledIcon` prop to `Toggle` to show a lock next to a toggle in disabled state.
- Changed `Toggle` story to a stateful demo with clickable toggle.
- Styling of disabled && checked toggle state and toggle label to more closely reflect the design.

Added disabled icon and label to toggle

---

src/components/Modal/__snapshots__/story.storyshot
src/components/ScrollBox/__snapshots__/story.storyshot
src/components/ScrollBox/style.tsx
src/components/Select/__snapshots__/story.storyshot

resolves #167
**Changes** 🌀
- Horizontal scrollbar in component `ScrollBox` is not visible anymore when horizontal scrolling is not possible.

Removed unnecessary horizontal scrollbar in Scrollbox

---

src/components/Modal/__snapshots__/story.storyshot
src/components/Modal/index.tsx
src/components/Modal/story.tsx
src/components/Modal/style.tsx

resolves #175 #173 
**Adds** ✨
- Additional modal size with width of 1068px
**Changes** 🌀
- 'large' modal variant is now 'medium', 'large' is replaced with a wider variant
- Eventlistener behavior has been changed to only close the modal when the modal overlay is the event target.
- `Modal` components using the 'large' variant need to change this to 'medium' to retain the same size! 'medium' is now the same size 'large' used to be while 'large' has become larger.

Added additional modal size

---

src/components/FormRow/__snapshots__/story.storyshot
src/components/FormRow/index.tsx

**Changes** 🌀
- The flex-basis from the label-box in the form-row from: `420px` to: `233px`

changed label flex-basis to 233px

---

package-lock.json
src/components/Checkbox/__snapshots__/story.storyshot
src/components/Checkbox/index.tsx
src/components/FormRow/__snapshots__/story.storyshot
src/components/RadioButton/__snapshots__/story.storyshot
src/components/RadioButton/index.tsx
src/components/RadioButtonGroup/__snapshots__/story.storyshot
src/components/TextField/formatters/withCurrencyFormatting/__snapshots__/story.storyshot
src/components/TextField/index.tsx
src/components/Toggle/__snapshots__/story.storyshot
src/components/Toggle/index.tsx

**Changes** 🌀
- Form Elements (`TextField`, `CheckBox`, `RadioButton`, `Toggle`) now have an optional `id` prop which can be used to specify labels for them.
- `Toggle`'s margin has been changed to match the rest of the form elements and thus align in the same way.

Added id's to form elements and margin to Toggle

---

src/components/Select/index.tsx
src/components/Select/test.tsx

**Adds** ✨
The following key handling has been added to replicate default behaviour:
- Select can now also be opened with arrow down and arrow up
- Tabbing while the select is open is now impossible
- Closing the select with Escape is now possible
- Selecting an option can be done with space
**Changes** 🌀
- Some options were hard or impossible to select this bug has now been resolved.

All select options are now clickable + added key shortcuts

---

src/components/Modal/__snapshots__/story.storyshot
src/components/ScrollBox/__snapshots__/story.storyshot
src/components/ScrollBox/style.tsx
src/components/Select/__snapshots__/story.storyshot
src/components/Select/index.tsx
src/components/Select/story.tsx
src/components/Select/style.tsx
src/components/Select/test.tsx

**Changes** 🌀
- `Select` now supports alternative input rendering. Added a story showing alternative input and option rendering.
- Fixes broken scroll in `Select`

Added alternative input rendering option to Select 

---

src/components/Modal/__snapshots__/story.storyshot
src/components/ScrollBox/__snapshots__/story.storyshot
src/components/ScrollBox/style.tsx

**Adds** ✨
- A z-index to the top/bottom shadows in the `ScrollBox` component.

Added z-index to Scrollbox shadows

---

src/components/Box/index.tsx
src/components/ButtonGroup/index.tsx
src/components/Contrast/index.tsx
src/components/EmptyState/index.tsx
src/components/Heading/index.tsx
src/components/Icon/index.tsx
src/components/Illustration/index.tsx
src/components/Link/index.tsx
src/components/MessageStream/index.tsx
src/components/Notification/index.tsx
src/components/Popover/index.tsx
src/components/PriceTag/index.tsx
src/components/Raised/index.tsx
src/components/Spacer/index.tsx
src/components/Text/index.tsx
src/components/TransitionAnimation/index.tsx

This PR is the result of a codeMod. It replaced StatelessComponent identifiers with SFC.
**Changes** 🌀
- StatelessComponent not used anymore, only SFC.

replaced StatelessComponent identifiers with SFC

---

src/components/Range/__snapshots__/story.storyshot
src/components/Range/index.tsx

Adds padding between textfields and Range after mistakingly removing them in a previous pr 🤐 

Fixed range padding

---

src/components/Modal/__snapshots__/story.storyshot
src/components/Modal/style.tsx
src/components/ScrollBox/__snapshots__/story.storyshot
src/components/ScrollBox/style.tsx
src/components/Select/__snapshots__/story.storyshot

resolves #222 
**Adds** ✨
- `overflow` to ScrollBox to fix disappearing button row in Modal
**Changes**
- `height` to `100vh` to fix height issue in IE11

Fixed Modal height/fixed button row issues

---

config/jest/setup.tsx
src/components/Popover/__snapshots__/story.storyshot
src/components/Popover/__snapshots__/test.tsx.snap
src/components/Popover/index.tsx
src/components/Popover/story.tsx
src/components/Popover/test.tsx
src/index.test.ts

resolves #196
**Changes** 🌀
- There is now optional internal state management for `Popover`. A method for triggering the Popover can be passed using the new `triggerOn` prop allowing `Popover` to be triggered by hovering or click it's children.
- `Popover` can now be closed by click outside.

Added eventlisteners to Popover for optional internal state management

---

src/components/FormRow/__snapshots__/story.storyshot
src/components/Range/__snapshots__/story.storyshot
src/components/TextField/formatters/withCurrencyFormatting/__snapshots__/story.storyshot
src/components/TextField/index.tsx
src/components/TextField/style.tsx
src/themes/MosTheme/MosTheme.theme.ts

When the Inputfield has feedback the severity color will be used as box-shadow. 
Also the icon wil only be shown if there's a feedback message. 
**Changes** 🌀
- Inputfield severity color used as box-shadow. 
- Feedback icon wil only be shown if there's a feedback message. 
- Inputfield theme changes.

Inputfield - improved focus and feedback

---

config/typescript/tslint.json
src/components/Badge/__snapshots__/story.storyshot
src/components/Badge/index.tsx
src/components/Badge/story.tsx
src/components/MultiButton/story.tsx
src/components/Select/__snapshots__/story.storyshot
src/components/Select/style.tsx
src/themes/MosTheme/MosTheme.theme.ts

Added a `severity`-prop to the badge component, to give the possibility to use the badge component with more colors.
**Adds** ✨
- Component `Badge` has now an optional `severity` prop. Default severity is `error`.

Added severity prop to the badge component

---

src/components/Modal/__snapshots__/story.storyshot
src/components/Modal/style.tsx

The css rule `height: 100vh;` is now only applied to IE11 browsers, restoring the prefered behaviour on the newer browsers. 
This does mean that the modal will stil be streched on IE11, i haven't found a suitable solution for this. 
resolves #231 
**Changes** 🌀
- Css rule `height: 100vh;` is now only applied to IE11 browsers, restoring the prefered behaviour on the newer browsers.

modal now only too large in IE11

---

src/components/Box/__snapshots__/story.storyshot
src/components/Branch/__snapshots__/story.storyshot
src/components/BreakpointProvider/__snapshots__/story.storyshot
src/components/EmptyState/__snapshots__/story.storyshot
src/components/ErrorBoundary/__snapshots__/story.storyshot
src/components/FoldOut/__snapshots__/story.storyshot
src/components/FormRow/__snapshots__/story.storyshot
src/components/FormRow/story.tsx
src/components/InlineNotification/__snapshots__/story.storyshot
src/components/Link/__snapshots__/story.storyshot
src/components/MessageStream/__snapshots__/story.storyshot
src/components/Modal/__snapshots__/story.storyshot
src/components/RadioButton/__snapshots__/story.storyshot
src/components/RadioButtonGroup/__snapshots__/story.storyshot
src/components/ScrollBox/__snapshots__/story.storyshot
src/components/Select/Option/__snapshots__/test.tsx.snap
src/components/Select/__snapshots__/story.storyshot
src/components/Spacer/__snapshots__/story.storyshot
src/components/Table/__snapshots__/story.storyshot
src/components/Text/__snapshots__/story.storyshot
src/components/Text/__snapshots__/test.tsx.snap
src/components/Text/style.tsx
src/components/TextArea/__snapshots__/story.storyshot
src/components/TextField/__snapshots__/story.storyshot
src/components/Toaster/__snapshots__/story.storyshot
src/components/Toggle/__snapshots__/story.storyshot

It turned out that using `flex: 1` in the styling of `Text` to make text wrap in IE in the specific context of the `FormRow` story was causing problems in other applications without fixing any issues outside of the formrow story. Therefore `flex: 1` was removed and the stories were adjusted to render properly.
**Changes** 🌀
- `FormRow` story to remove unnecessary Box components and render properly in IE.
**Removes** 👋
- Problematic `flex: 1` in `Text` `style.tsx`.
- Feature `foo` no longer supports `foo` and needs to be converted to `foop`

Fixed IE flexbox issue in Text and stories in FormRow that were affected by this issue

---

src/components/Checkbox/__snapshots__/story.storyshot
src/components/Checkbox/index.tsx
src/components/Checkbox/style.tsx
src/components/FormRow/__snapshots__/story.storyshot
src/components/FormRow/index.tsx
src/components/FormRow/style.tsx
src/components/InlineNotification/__snapshots__/story.storyshot
src/components/Link/__snapshots__/story.storyshot
src/components/MessageStream/__snapshots__/story.storyshot
src/components/Modal/__snapshots__/story.storyshot
src/components/MultiButton/__snapshots__/story.storyshot
src/components/Popover/__snapshots__/story.storyshot
src/components/PriceTag/__snapshots__/story.storyshot
src/components/RadioButton/__snapshots__/story.storyshot
src/components/RadioButtonGroup/__snapshots__/story.storyshot
src/components/Raised/__snapshots__/story.storyshot
src/components/Range/__snapshots__/story.storyshot
src/components/ScrollBox/__snapshots__/story.storyshot
src/components/Select/__snapshots__/story.storyshot
src/components/Skeleton/__snapshots__/story.storyshot
src/components/Spacer/__snapshots__/story.storyshot
src/components/Table/__snapshots__/story.storyshot
src/components/TextArea/__snapshots__/story.storyshot
src/components/TextField/__snapshots__/story.storyshot
src/components/Tile/__snapshots__/story.storyshot
src/components/Toaster/__snapshots__/story.storyshot
src/components/Toggle/__snapshots__/story.storyshot
src/components/TransitionAnimation/__snapshots__/story.storyshot

The default offset on the `Checkbox` has been removed in this PR. The offset was often unnecessary, but always required in the FormRow. 
The FormRow style now adds this offset on the checkbox. 
**Changes** 🌀
- Checkbox has no default offset
- Checkbox in Table aligns correctly

Removed default offset from checkbox

---

src/components/FormRow/__snapshots__/story.storyshot
src/components/Range/__snapshots__/story.storyshot
src/components/TextField/__snapshots__/story.storyshot
src/components/TextField/index.tsx
src/components/TextField/test.tsx

removed onFocus- onBlurCapture from wrapper to prevent double focus.
resolves #256  
**Changes** 🌀
- removed onFocus- onBlurCapture from wrapper to prevent double focus

removed onFocus- onBlurCapture from wrapper to prevent double focus

---

src/components/Popover/__snapshots__/story.storyshot
src/components/Select/__snapshots__/story.storyshot
src/components/Select/style.tsx

There were some issues with the grey background/focus thing of `Select` not showing up when using it in other pages due to the `StyledWrapper` z-index. This is a fix.
**Changes** 🌀
- z-index of `StyledWrapper` in `Select`

Fixed select StyledWrapper z-index bug

---

src/components/FormRow/__snapshots__/story.storyshot
src/components/RadioButton/__snapshots__/story.storyshot
src/components/RadioButton/style.tsx
src/components/RadioButtonGroup/__snapshots__/story.storyshot

Resolves a layering bug with the RadioButton. The center circle is rendered on top of the overlay due to the OVER 9000!! z-index:
**Removes** 👋
- `z-index` from center circle in RadioButton

Removed z-index from RadioButton center

---

package.json
src/components/TextField/formatters/withNumberFormatting/index.tsx
src/components/TextField/formatters/withNumberFormatting/test.tsx
src/components/TextField/story.tsx

Fixes a behavior in `TextField.Number` that didn't allow it to be empty. It also saves the last valid input and restores that on blur when invalid input is given (as discussed with luuk).
**Changes** 🌀
- Fixes `Textfield.Number` behavior.

Fixed TextField.Number to allow it to be empty

---

Dockerfile
package-lock.json

Somehow the now deploys got broken. This fixes them and adds a step where package-lock is copied to the deployment to make sure it's running the same config we are.
`patch`

Fix for Now deploys

---

src/components/TextField/formatters/withCurrencyFormatting/index.tsx
src/components/TextField/formatters/withCurrencyFormatting/test.tsx
src/components/TextField/story.tsx

resolves #271 
- [ x ] I have exported my addition from `src/index.ts` (check if not applicable)
- [ x ] Appropriate tests have been added for my functionality (check if not applicable)
- [ x ] A designer has seen and approved my changes (check if not applicable)
- [ x ] I have tested my addition in all supported browsers and for responsiveness (Chrome, Firefox, Safari, Edge, IE11 and mobile browsers)
**Adds** ✨
- disableNegative prop, just like the NumberFormatter

Added disableNegative prop to CurrencyFormatter

---

.github/PULL_REQUEST_TEMPLATE.md

Changes this template to ⤵️ 
[issue description]
-- or --
resolves #[resolved issue number]
- Component `Foo` has been removed.
- Component `Bar` no longer supports prop `x`, you should use prop `y` from now on.
- Component `FooBar` has been redesigned.
- Component `Foo` now also supports an optional `size` props to increase it's size.
- The new component `Bar` has been added.
- Component `Foo` now uses the correct icon.
- Refactored some components.

Changed pr template to better identify semver

---

src/components/Select/__snapshots__/story.storyshot
src/components/Select/index.tsx
src/components/Select/test.tsx

Add handling of a (simulated) change event to the Select. This makes it easier to test and possibly makes it more interchangeable with an actual html select
**Adds** ✨
- Change event handling for Select
- A test to cover this

Select handles change events

---

src/components/Select/index.tsx
src/components/Select/test.tsx

- `Select` instantly triggered the `onChange` callback once you started entering a value. This is fixed.

Select no longer triggers a change when a value is entered

---

src/components/TextField/formatters/withCurrencyFormatting/index.tsx
src/components/TextField/formatters/withCurrencyFormatting/test.tsx
src/components/TextField/story.tsx

When dealing with currency values, it is best practice to work with the the amount in minor values. This pr adds a prop that internalizes this behavior in the input.
- Component `TextField.Currency` now also supports an optional `minor` prop, to enable working with minor units.

Textfield.Currency supports minor units

---

src/components/Box/index.tsx
src/components/Box/story.tsx
src/components/Box/style.tsx
src/components/Box/test.tsx
src/types/OffsetType.ts
src/utility/trbl/index.ts

resolves #280 
- `Box` now supports an array directly in it's `margin` and `padding` prop. 
`<Box margin={trbl(0, 12} />` now becomes: `<Box margin={[0, 12]} />`

Added shorthand tuple to Box

---

src/components/ButtonGroup/index.tsx
src/components/Modal/index.tsx
src/components/Modal/story.tsx
src/components/Modal/style.tsx
src/components/Modal/test.tsx

- Added support to render an array of buttons
- Added a way to skip the breakpointprovider in buttongroups
- Made the styling conform design specs
- Made the title editable in storybook
- Deprecation warning in console and docs
- None.
- Component `modal` now also accepts an array of Reactnodes to use in the button bar.
- Conformed the styling to the design specs.

Improved modal responsiveness

---

src/components/EmptyState/index.tsx
src/components/EmptyState/test.tsx

Fixed rendering of the button prop on EmptyState when no children are present in the EmptyState
- the button wasn't rendered when children where also rendered in the EmptyState.

Fixed rendering of the button prop on EmptyState

---

src/themes/MosTheme/MosTheme.theme.ts

h4 used wrong font
- Component `Heading` h4 now uses the correct font.

Changed h4 from bodyFont to headingFont

---

src/components/Breadcrumbs/index.tsx
src/components/Heading/index.tsx
src/components/Heading/story.tsx
src/components/Heading/test.tsx
src/components/Text/story.tsx
src/themes/MosTheme/MosTheme.theme.ts

resolves #315 
- A new hierarchy is introduced to the Heading.
- The Heading key in the theme is now an array.
- light is removed as a prop on Heading.
- Breadcrumbs now have the correct color

Removed light font weight

---

src/components/TextField/style.tsx

resolves #310
- None
- None
- Added a min-width to the input field. Firefox has an internal/default minimal width that caused this issue. By setting it to a much lower value the issue is resolved.

Added min-width to fix rendering issue in firefox

---

src/components/Button/story.tsx
src/components/Button/style.tsx

resolves #130 
With `translate3d`:
without `translate3d`:
- Button transform property is changed to `none` to fix Safari anti-aliasing issue

Removed translate3d from Button idle state

---

src/components/Range/style.tsx

Dot where sized by REM, which made them have an alternative size based on font-size used in applications.
- The dots on the `Range` component now het a fixed size.

Fixed rem based dots

---

src/components/Button/index.tsx
src/components/IconButton/index.tsx
src/components/IconButton/story.tsx
src/themes/MosTheme/MosTheme.theme.ts

Resolves: #313
The `IconButton` in the `1.x` branch had no focus state styling. Therefor it inherited styling which is commonly defined in applications, like `background` and `color`. It now has explicit styling for hover, focus, and active states. This inludes a fallback to `idle` when in a `loading` state, which was undefined before. This is fallback is also applied to `Button`.
- Adjusted IconButtonThemeType
- Button & IconButton have explicit styling

Explicit state styling on (Icon)Button

---

src/themes/MosTheme/MosTheme.theme.ts

Mentioned I would do this in #325 as preparation for theme interpolation from narrow theme. 
- Theme now uses rgba converter and color variables (where applicable) instead of hardcoded rgba strings.

Converted hardcoded rgba strings to use color variables

---

src/components/Toast/style.tsx

resolves SCS-340
- none
- none
- The wrapper element gets a `pointer-events: none` to prevent getting stuck in IE11.

Toaster : Added pointer events to fullscreen wrapper

---

src/components/Checkbox/index.tsx
src/components/Checkbox/story.tsx
src/components/FormRow/story.tsx
src/types/OffsetType.ts

Adds the ability to render a label next to a Checkbox
- Component `Checkbox` now also supports an optional `label` prop.

Checkbox label

---

src/components/Range/index.tsx
src/components/Table/TableHeaders/index.tsx

To (slighty) improve a11y I checked which components are usable with only the keyboard. All of them were apart from `Table` and there was a slight bug in `Range` when using the keyboard. Both of these issues are fixed in this PR.
- It is now possible to sort a `Table` using only the keyboard
- It is no longer possible to enter a value outside of the min/max limit on the Range using the keyboard

Improved keyboard navigation

---

src/components/Badge/index.tsx
src/components/Badge/test.tsx
src/components/Box/test.tsx
src/components/Breadcrumbs/index.tsx
src/components/Breadcrumbs/test.tsx
src/components/Button/base/index.tsx
src/components/Button/index.tsx
src/components/Button/test.tsx
src/components/ButtonGroup/index.tsx
src/components/ButtonGroup/test.tsx
src/components/Checkbox/index.tsx
src/components/Checkbox/test.tsx
src/components/EmptyState/index.tsx
src/components/EmptyState/test.tsx
src/components/Link/index.tsx
src/components/Link/test.tsx
src/components/Modal/index.tsx
src/components/Select/Option/index.tsx
src/components/Select/index.tsx
src/components/Select/story.tsx
src/components/Select/test.tsx

A little bit of progress for #249
-  Removed `data-test="bricks-select-collapse"` from Select
- Added `data-testid` as a prop to Select, Button and Link for better testability
- Refactored some tests.

Added test-id to multiple components

---

package-lock.json
package.json
src/components/Range/index.tsx
src/components/Range/story.tsx
src/components/Range/test.tsx

Fixes the issue with decimal values in the range input slider. Previously a values of `1.75` was not selectable and rounded by the input to 2. 
In consultation with UX (rianne) this fix was made: min values are now floored to the nearest whole number (1.75 > 1) and the max value is now ceiled to the nearest whole number (15.2 > 16). And thus decimals are not shown and used.
- None.
- None
- Non-whole values are floored (min value) and ceiled (max value) now.

SCS-470 : Range Slider value to whole numbers

---

src/components/TextField/index.tsx
src/components/TextField/story.tsx
src/components/TextField/style.tsx
src/components/TextField/test.tsx
src/themes/MosTheme/MosTheme.theme.ts

- Component `TextField` now also supports an optional `placeholder` prop to show a placeholder value.

Added placeholder prop

---

src/components/FormRow/index.tsx
src/components/FormRow/story.tsx

- Component `FormRow` now also supports a `badge` prop to add a badge to the label. This prop takes an element and renders it to the top-right of the label.

Added badge to FormRow

---

src/components/Modal/style.tsx

- Allow the modal to have a greater max-height

Tweaked modal max-height

---

src/components/Toggle/index.tsx
src/components/Toggle/story.tsx

Sometimes the toggle will not be disabled but it will be unavailable. In this case the label should be greyed out and an alternative action is called on the `onChange` of the toggle.
- Component `Toggle` now also supports an `unavailable` prop which greys out the label

Add unavailable prop to toggle

---

src/components/Box/index.tsx
src/components/Box/story.tsx
src/components/Box/style.tsx
src/components/Box/test.tsx

Adds z-index as prop to Box
- Component `Box` now also supports an optional `zIndex` props to increase it's z-index.

Added z-index to box

---

src/components/RadioButton/story.tsx
src/components/RadioButton/style.tsx

I noticed the labels of the RadioButtons were not aligned to the center of the button.
- Set align-items to center for flex container of `RadioButton`

Align RadioButton labels to center

---

src/components/Button/base/index.tsx
src/components/Button/test.tsx
src/components/Link/index.tsx
src/components/Link/test.tsx

- The `onClick` prop of `Button`, `IconButton` and `Link` now receives the click event as an argument to the callback.

passed click event to button components onClick callback

---

src/components/Slider/index.tsx
src/components/Slider/story.tsx
src/components/Slider/test.tsx

resolves [STRF-160](https://myonlinestore.atlassian.net/browse/STRF-160)
- Component `Slider` now also supports a couple of optional props: `hideInputField`, `onFocus`, `onBlur`

Additional Slider props

---

src/components/PriceTag/index.tsx
src/components/PriceTag/test.tsx

Like the TextField.Currency, with this PR the `PriceTag` now also support ISO-15897 locales. (nl_NL, en_GB)
- Like the TextField.Currency, with this PR the `PriceTag` now also support ISO-15897 locales. (nl_NL, en_GB)

Added support for ISO-15897 locales to pricetag

---

CONTRIBUTING.md
docs/README.md
docs/components/Page.tsx
docs/lib/componentMap.tsx
docs/next-env.d.ts
docs/next.config.js
docs/package.json
docs/pages/_app.tsx
docs/pages/components.tsx
docs/pages/index.tsx
docs/yarn.lock
package.json
scripts/copy-readme.js
src/components/Badge/readme.mdx

This PR sets up content management for the docs website by pulling from readme files. We could use github as a "versioned CMS" since you can edit a file without knowing anything about git through the github web app.
- The docs-site can now take content from readme.mdx files colocated in component folders.

Added doc generation to docs website

---

src/components/TextField/formatters/withCurrencyFormatting/test.tsx
src/components/TextField/formatters/withNumberFormatting/test.tsx
src/components/TextField/index.tsx
src/components/TextField/test.tsx

- Textfield is now testable with a data-testid

Textfield is now testable with a data-testid

---

src/components/Select/test.tsx
src/components/Table/test.tsx
src/themes/MosCorporateTheme/theme.ts
src/themes/MosTheme/MosTheme.theme.ts
tslint.json

Removes TSLint rule `max-file-line-count` as we disable it when necessary making it only a nuisance and not a help.
- Disable `max-file-line-count` rule in TSLint

Disable 'max-file-line-count' in tslint and remove all references

---

src/components/FormRow/index.tsx
src/components/FormRow/story.tsx

resolves #382 
This renders Skeletons in the `FormRow` the same as before the introduction of the `badge` prop.
- Skeleton now renders properly in the label field of a `FormRow` again.

Correctly render Skeletons in a FormRow

---

src/components/Toast/index.tsx
src/components/Toast/story.tsx
src/components/Toast/test.tsx

Adds the possibility to add a secondary button to a toast as well as the option to make a toast persistent, meaning that it has no close button and cannot autodismiss.
- `secondaryButtonTitle`, `onClickSecondary` and `persistent` props to `Toast`

Add optional secondary button and persistent option to Toast

---

src/components/RadioButton/index.tsx
src/components/RadioButton/test.tsx
src/components/Text/test.tsx

Makes the radiobutton testable with a data-testid prop.
- RadioButton is not testable with a data-testid
- Wrote some test to cover the testid
- Rewrote the Radiobutton to hooks. 
- Added a test for the Text component, since it is already testable with a testid.

Radio testid

---

src/components/ButtonGroup/index.tsx
src/components/ButtonGroup/story.tsx
src/components/ButtonGroup/test.tsx

resolves #424 
- switched the button order from flexbox reverse-row to an array reverse. This way the order isn't just perceived.

Fix buttongroup focus order

---

src/components/Raised/index.tsx
src/components/_MerchantTheme/sampleContent.tsx

resolves #438 
- Removes `padding` and `width` from `Raised`

fix: Raised styling no longer has padding and width

---

src/components/Box/index.tsx
src/components/Box/style.tsx
src/components/Box/test.tsx

The box missed to `as` prop that can be passed to the styled-component this PR fixes that.
- None
- None
- Correctly typed the as prop on the Box
- Also used the as prop internally.

Added as prop to Box

---

src/components/Toast/index.tsx
src/components/Toast/test.tsx

- Toast (and thus window.notify) is now testable with a data-testid
- Refactored Toaster to hooks

Added data-testid to Toaster and refactored it to hooks

---

src/components/FoldOut/style.tsx

resolves #442 
- Overflow is now visible when `FoldOut` is open

FoldOut: Set overflow to visible when opening foldout and animate transition

---

src/components/Popover/index.tsx

Adds a prop arrowStyle to the popover component that passes an object with css properties to the arrow rendered in react-popper.

Popover : added arrowStyle prop

---

src/components/Toaster/index.tsx
src/components/Toaster/test.tsx

- Adds a callback that gets fired on a toaster.notify to the Toaster. 

Added onNotify callback to toaster

---

src/components/TextField/index.tsx
src/components/TextField/story.tsx
src/components/TextField/style.tsx
src/components/TextField/test.tsx

- None
- The `prefix` and `suffix` props on `TextField` now also take ReactNodes instead of only strings
- The TextField component story refactored from class to FC and cleaner code with less duplication
Result:
Left is a Checkbox, right a clickable IconButton.

Refactored textfield story + added component support to affix props

---

src/components/TextField/index.tsx
src/components/TextField/story.tsx
src/components/TextField/test.tsx

This PR:
resolves #BIER-1250
Backwards compatible additions ✨
Added an optional showClearButton prop
This prop shows a button that returns an empty string in the onChange callback when clicked
Checklist 🛡
I have exported my addition from src/index.ts (check if not applicable).
Appropriate tests have been added for my functionality (check if not applicable).
A designer has seen and approved my changes (tag @LuukHorsmans or @RianneSchaekens for a design review when applicable).
I have tested my addition in all supported browsers and for responsiveness (Chrome, Firefox, Safari, Edge, IE11 and mobile browsers).
Appropriate documentation has been written (check if not applicable).
WARNING: this PR is based on SCS-1065.

TextField : clear field callback

---

src/components/TextField/index.tsx
src/components/TextField/story.tsx

The clear-button in TextField used a plain icon. This is now replaced with an IconButton, to make sure the interaction (hover) is the same as other buttons, for example the action buttons used in tables.

refactored textfield to use IconButton to clear the field

---

src/components/ButtonGroup/index.tsx
src/components/Modal/index.tsx
src/components/Modal/story.tsx
src/components/Modal/test.tsx

- None
- A centered prop to the Modal that centers the heading and buttons.
- None

Modal centered

---

src/components/TextArea/index.tsx
src/components/TextArea/story.tsx
src/components/TextArea/test.tsx

Adds an optional character limit to `TextArea`
- Component `TextArea` also supports optional `characterLimit` prop

Added character limit to TextArea

---

src/components/Tooltip/index.tsx
src/components/Tooltip/style.tsx

Adjusts the z-index of the Tooltip window so it lays on top of appending nodes
- Rearranged TooltipWindow

Added TooltipWindow z-index

---

src/components/Button/base/index.tsx

`onMouseEnter` and `onMouseLeave` on ButtonBase were only passed on the anchor. With this PR they're passed on the button element as well.
- passes `onMouseEnter` and `onMouseLeave` on ButtonBase as `button` as well

Added onMouseEnter and onMouseLeave to ButtonBase

---

src/components/TextArea/index.tsx
src/components/TextArea/style.tsx
src/themes/MosTheme/MosTheme.theme.ts

- Adds `data-testid` to TextArea element
- Changes padding so native ui elements don't float (scrollbar and resize icon)
- Added onClick to characterLimit box to focus the textarea
- Refactored to Functional Component
- Fixed text color

Added testid to TextArea and adjusted padding and color

---

src/components/PriceTag/index.tsx
src/components/PriceTag/story.tsx
src/components/PriceTag/test.tsx

Adds the ability to use minor units in the PriceTag
- `minor` prop on `PriceTag`

Added minor prop to PriceTag to handle minor units

---

.github/workflows/deploy.yml

- This makes sure GitHub recognizes the actual CI account as a user. Could be useful for stats in the future

Add actual ci user to GitHub action

---

src/components/TextField/formatters/withNumberFormatting/index.tsx
src/components/TextField/formatters/withNumberFormatting/test.tsx
src/components/TextField/index.tsx
src/components/TextField/story.tsx

Resolves #483
- Added optional `allowDecimals`, `locale`, `minimumFractionDigits` and `maximumFractionDigits` to `TextField.Number`

Added float support to TextField.Number

---

src/components/Checkbox/index.tsx
src/components/Checkbox/test.tsx

I discovered the `Checkbox` still handled it's `onChange` when disabled. This PR prevents `props.onChange` from being called and adds a test to ensure it.
- `onChange` no longer fires when disabled is true.

Prevented firing of onChange when checkbox is disabled

---

docs/components/ContentPane.tsx
docs/components/Page.tsx
docs/components/SidebarLink.tsx
docs/containers/Header.tsx
docs/lib/componentMap.tsx
docs/pages/_error.tsx
docs/pages/index.tsx

Replaces hardcoded `style` prop styling and colors with styled components and colors from bricks in the design system site.

Use styled-components instead of style prop, replace hardcoded colors

---

src/components/ButtonGroup/index.tsx
src/components/ButtonGroup/test.tsx

resolves #455 
- Removes (deprecated) `stacked` prop on `ButtonGroup`

#455 - Remove deprecated stacked prop on ButtonGroup

---

src/components/PriceTag/style.tsx
src/components/PriceTag/test.tsx
src/themes/ExperimentalCustomTheme/genTheme.ts
src/themes/MosTheme/MosTheme.theme.ts
src/types/ThemeType/index.ts

resolves #433 
- Replace separate strikethrough theme properties for pricetag with font colour.

#433 - Use font colour for strikethrough PriceTag

---

docs/lib/componentMap.tsx
src/components/Breadcrumbs/index.tsx
src/components/EmptyState/index.tsx
src/components/FormRow/story.tsx
src/components/InlineNotification/index.tsx
src/components/MessageStream/index.tsx
src/components/MultiButton/index.tsx
src/components/RadioButton/index.tsx
src/components/Select/Option/index.tsx
src/components/Select/index.tsx
src/components/Select/story.tsx
src/components/Table/Card/index.tsx
src/components/Table/Row/index.tsx
src/components/Table/TableHeaders/index.tsx
src/components/Table/story.tsx
src/components/Text/index.tsx
src/components/Text/story.tsx
src/components/Text/test.tsx
src/components/TextArea/index.tsx
src/components/Toast/index.tsx
src/components/Toast/style.tsx
src/components/Toggle/index.tsx
src/components/_CustomTheme/sampleContent.tsx
src/themes/MosTheme/MosTheme.theme.ts

resolves #431 
- Refactor `variant` prop on `Text` into `size` prop
- Refactor `severity` prop on `Text` into `variant` and add `descriptive` as variant.

431 - Refactor variant -> size, severity -> variant in Text component

---

src/components/IconButton/index.tsx

Adds explicit background styling to the IconButton to prevent unwanted style inheritance on hover/focus/active states:
- none
- none
- Adds explicit background styling to prevent unwanted style inheritance on hover/focus/active states.

Added explicit styling to IconButton states

---

.github/workflows/deploy.yml
docs/CNAME
docs/components/Head.tsx
docs/lib/articles-to-pages.js
docs/package.json
docs/pages/index.tsx
docs/yarn.lock

Deploys the design system website to GH pages instead of storybook. Storybook will remain visible on the Now deploys.

Deploy design system site instead of storybook to GH pages

---

docs/components/ColorBoard.tsx
docs/markdown/design/colors.mdx

Add color board component to colors design page in docs site.
- Color board 🌈 

Add color board component

---

.github/workflows/deploy.yml
now.json
package.json
packages/components/package.json
rollup.config.js

Fix storybook deploys and update paths for GH pages deploys. Since the `builds` field in the `now.json` is deprecated (https://zeit.co/docs/configuration#project/builds) I added a `now-build` script in the root package.json. 

Fix now2 and GH pages deploys for 2.x

---

packages/assets/package.json
packages/assets/scripts/types.js

It is currently impossible to set props like "width" and "style" on an svg element exported from `@myonlinestore/bricks-assets`. This PR adds the correct types.
`@myonlinestore/bricks-assets` now exports types with correctly typed props.

Added correct types to svg components

---

packages/components/src/components/Button/index.tsx

resolves broken styling. The hover state and underline were missing.
- none
- none
- `;`

Fix broken styling on plain Button variant

---

packages/components/docs/components/PreviewPane.tsx
packages/components/docs/containers/examples/ButtonExamplesContainer.tsx
packages/components/docs/markdown/components/buttons.mdx
packages/components/docs/package.json
packages/components/docs/yarn.lock
packages/components/src/components/Contrast/index.tsx

Adds a `PreviewPane` components to the Design System site. This component can be used with `options` and `examples` props to show examples of usages of components.
- `PreviewPane` component for the DS site.
- `Contrast` now passes `className` to allow custom styling

Design System - Add PreviewPane component

---

packages/components/docs/containers/Header.tsx

Makes the header navigation link to a category link to the first article in that category instead of to a generic index page.

Design System: Automatically link to first article in a category

---

packages/components/src/components/FormRow/index.tsx
packages/components/src/components/FormRow/story.tsx
packages/components/src/components/FormRow/style.tsx
packages/components/src/themes/CustomTheme/genTheme.ts
packages/components/src/themes/MosTheme/MosTheme.theme.ts
packages/components/src/types/OffsetType/index.ts
packages/components/src/types/ThemeType/index.ts

- FormRow is now part of the ThemeType to decide it's disabled styling.
- `disabled` prop added to `FormRow`
- Added a styled component to the `FormRow` that renders a disabled variant of the text.

feat: implement 3.0 FormRow design 

---

README.md
lerna.json
package.json
packages/assets/package.json
packages/components/package.json

adds  a `release` task so we can publish packages with Lerna. It is configured to version packages separately and uses the conventional commits to generate release notes in the CHANGELOG.md inside the package.

chore: add release task for publishing

---

packages/components/src/components/Toggle/index.tsx

The new Toggles did not align properly in the FormRows because they're smaller. With this adjustment everything looks great again 😎 .
- Toggle margin

fix: Toggle margin

---

packages/components/src/components/Button/index.tsx
packages/components/src/components/Checkbox/index.tsx
packages/components/src/components/FormRow/index.tsx
packages/components/src/components/FormRow/story.tsx
packages/components/src/components/Separated/index.tsx
packages/components/src/components/Separated/test.tsx
packages/components/src/components/TextArea/style.tsx
packages/components/src/components/TextField/style.tsx
packages/components/src/components/TextualButton/index.tsx
packages/components/src/components/Toggle/index.tsx
packages/components/src/themes/MosTheme/MosTheme.theme.ts
packages/components/src/types/OffsetType/index.ts

- Add a :focus:hover state to buttons, buttons still have a hover even when focused
- Labels and form fields didn't align correctly.
- The plain button still had incorrect styling
- The line under the textual button seems to be positioned a bit too far down:

fix: Bricks 3.0 - Styling Improvements

---

packages/components/src/components/Checkbox/index.tsx
packages/components/src/components/RadioButton/index.tsx
packages/components/src/components/RadioButton/style.tsx
packages/components/src/components/Toggle/index.tsx

With multiline labels, the Toggle/Checkbox/RadioButton placement in formrows was off.
- Align the Toggle/Checkbox/RadioButton and Label to `flex-start` instead of `center`.

fix: Ensure correct placement with multiline labels

---

packages/components/src/components/Button/index.tsx

Removes the ::before that is no longer serving any function.
- Removes ::before from buttons.

fix(Button): Remove ::before

---

packages/components/package.json
packages/components/src/components/Checkbox/index.tsx
packages/components/src/components/Checkbox/story.tsx
yarn.lock

- Replaces icon used to indicate "indeterminate" state `Checkbox`
- [] A designer has seen and approved my changes (tag `@LuukHorsmans` or `@RianneSchaekens` for a design review when applicable).

fix: Bricks 3.0 - Replace indeterminate state Checkbox icon

---

packages/components/package.json
packages/components/src/components/Checkbox/index.tsx
packages/components/src/components/Checkbox/story.tsx
yarn.lock

Replaces intermediate state icon of Checkbox
- bricks-asset@0.2.0 peer dependency
- none
- Component `Checkbox` now uses the correct icon.

fix(Checkbox): replace intermediate state icon

---

packages/components/src/components/TextualButton/index.tsx
packages/components/src/themes/MosTheme/MosTheme.theme.ts

…tweight
Prevents overriding of `TextualButton` hover styles and changes the default fontWeight from 600 to 400
- `TextualButton fontweight 600 -> 400
- Explicitly set `TextualButton` hover styles to prevent overrides.

fix(TextualButton): Prevent hover styles being overridden, change fontweight

---

packages/components/src/components/Range/style.tsx
packages/components/src/components/Slider/style.tsx

Prevents disalignment of range and slider.
*Can be tested with `@myonlinestore/bricks@3.0.1-alpha.1`*

fix(Range, Slider): prevent overrides

---

packages/components/src/components/Button/index.tsx

The border of the plain button is sometimes not rendered in chrome after content on the page has shifted. This adds a transform that makes sure the button is rerendered correctly after moving. It can be tested using:
`@myonlinestore/bricks@3.0.1-alpha.2`
- Add transform to Plain button to make sure border renders in chrome.

fix(Button): Make sure plain button border is rendered in chrome

---

packages/components/src/components/InlineNotification/index.tsx

- Correct alignment of `InlineNotification` in case of multiple lines (ideally this never happens but sometimes it does)

fix(InlineNotification): align to flex-start instead of to center

---

packages/components/src/components/Carousel/index.tsx

Fixed a bug in the carousel styling which misaligns slide buttons
This occurs because left/right isn't properly closed, which leads to `left: 12px background: ...` as a single css rule.

fix(Carousel): Fixed a bug in the carousel styling which misaligns slide buttons

---

packages/components/docs/lib/componentMap.tsx

Removes `variant="descriptive"` from body text and lists. With the bricks 3.0 changes this is not desired anymore.

docs: fix design system paragraph text variant

---

packages/components/src/components/Table/TableHeaders/index.tsx
packages/components/src/components/Table/story.tsx

This PR fixes a visual inconsistency when toggling an `onDragEnd` on an empty (no rows) `Table` component
- None
- None
- Draghandler now has a fixed width, which avoids shifting tableheaders
- Added a story that allows you to reproduce this issue

fix(Table): Added fixed width to draghandler table header

---

packages/components/src/components/Select/SelectInput.tsx
packages/components/src/components/Select/SelectModal.tsx
packages/components/src/components/Select/index.tsx
packages/components/src/components/Select/style.tsx
packages/components/src/components/Select/test.tsx

Progress towards #548 next step would be to implement a context for the Select so SelectModal and SelectInput can be exposed as seperate components
- None
- None
- Select is now composed of SelectModal and SelectInput

refactor(Select): Split Select into subcomponents

---

packages/components/src/components/Select/SelectOption.tsx
packages/components/src/components/Select/SelectOptionGroup.tsx
packages/components/src/components/Select/index.tsx
packages/components/src/components/Select/story.tsx

- None
- Added `Select.OptionGroup` that allows you to add a hierarchy to the options
- None

feat(Select): Added Select.OptionGroup

---

packages/components/src/components/CurrencyField/index.tsx
packages/components/src/components/CurrencyField/test.tsx

- `onBlur`, `onFocus`, `onClick` are now called if defined.

fix(CurrencyField): execute onBlur, onFocus, onClick if defined

---

packages/components/src/components/Select/test.tsx

I thought I had found a bug related to `component.find(Select)` in a test. So I wrote a test to prove the bug, turns out the bug was behind the keyboard 🤦 . Still not a bad test to have though, so here we are...
- None
- None
- Added a simple test

test(Select): Added Select test for finding by instance

---

packages/components/src/components/Accordion/index.tsx

enables the Accordion to flex to full width of its parent.
- none
- none
- Added flex grow property to root element

fix(Accordion): Added flex grow property to root element

---

packages/components/src/components/Accordion/index.tsx
packages/components/src/components/Accordion/style.tsx
packages/components/src/components/Accordion/test.tsx

- Moved the button click area to the foldout icon for a better focus area

fix(Accordion): Moved button area

---

packages/components/src/components/TextArea/style.tsx
packages/components/src/components/TextField/style.tsx

The contents of a disabled textfield were not readable in Safari.
- disabled TextField contents are now readable in safari

fix(TextField): disabled TextField is now also readable in safari

---

packages/components/src/components/Accordion/style.tsx

- Resets hover and focus styles on Accordion

fix(Accordion): Reset styles explicitly

---

packages/components/src/components/Select/index.tsx

- None
- None
- The Select was handling a change twice, once on the actual click and once in a useEffect, which would cause weird behaviour and would make stale selected values show up. I fixed this by centralizing "reacting to changes" within the useEffect. This way the process around this is more straight forward and catches both cases.

fix(Select): No longer calls value changes twice

---

packages/components/src/components/InlineNotification/index.tsx
packages/components/src/components/Text/index.tsx
packages/components/src/components/TextField/index.tsx
packages/components/src/components/TextField/test.tsx

- None
- Feedback prop now supports a data-testid so you can test passed in feedback easier.
- Removed an obsolete test

feat(TextField): Feedback prop now supports a data-testid

---

packages/components/src/components/Toaster/index.tsx

- None
- By default the toaster container does not have any positioning. When no container is present, a fixed container positioned to the top is now rendered.
- None

feat(Toaster): Improved default positioning of toaster container

---

packages/components/src/components/TextArea/index.tsx
packages/components/src/components/TextArea/test.tsx

- None
- TextArea now supports `data-testid` on the feedback prop
- None

feat(TextArea): TextArea now supports data-testid on the feedback prop

---

packages/components/src/components/CurrencyField/index.tsx

`CurrencyField` didn't call `props.extractRef()`
- none
- none
- `CurrencyField` calls `extractRef` prop
<details> …

fix(CurrencyField): Call extractRef prop

---

packages/components/src/components/Button/base/index.tsx
packages/components/src/components/Button/base/test.tsx

- none
- Adds `onFocus` and `onBlur` to the buttons.
- none
<details>
_Tip: make sure the first commit message …

feat(Button): Added onFocus and onBlur props

---

packages/components/src/components/Table/Row/index.tsx
packages/components/src/components/Table/Row/test.tsx
packages/components/src/components/Table/TableHeaders/index.tsx
packages/components/src/components/Table/index.tsx
packages/components/src/components/Table/story.tsx
packages/components/src/components/Table/test.tsx

Adds the possibility to disable checkboxes in a table row.
- none
- `disabled` prop on a Table row
- Fixed a few tests
<details> …

feat(Table): Added disabled prop to row

---

packages/components/src/components/Select/SelectList.tsx
packages/components/src/components/Select/index.tsx
packages/components/src/components/Select/test.tsx

#577 
- None
- Options has been added to the `SelectContext`
- Empty text is shown again when no options are eligible for picking.

fix(Select): Empty text is shown again

---

packages/components/src/components/Skeleton/Rect/style.tsx

- None
- None
- Skeleton.Rect is now rendered as a span
<details>
_Tip: make sure the first commit message is …

fix(Skeleton): Turned rect skeleton into span to avoid invalid nesting

---

packages/components/src/components/TextArea/index.tsx
packages/components/src/components/TextArea/test.tsx

This PR adds an onBlur function to the TextArea component
- Component `TextArea` now supports an `onBlur` prop to handle onBlur callbacks.
<details>
_Tip: make sure …

feat(TextArea): Added onBlur prop

---

packages/components/src/components/PromotionBadge/index.tsx

- none
- none
- PromotionBadge is now rendered as a span instead of a div to prevent nesting errors
<details> …

fix(PromotionBadge): Now rendered as a span instead of a div

---

packages/components/src/components/RadioButton/index.tsx
packages/components/src/components/RadioButton/test.tsx

- Added check to prevent onChange when disabled
<details> …

feat(RadioButton): Added check to prevent onChange when disabled

---

packages/components/src/components/CurrencyField/index.tsx
packages/components/src/components/CurrencyField/test.tsx
packages/components/src/components/NumberField/index.tsx
packages/components/src/components/NumberField/test.tsx
packages/components/src/components/TextField/story.tsx

Adds the possibility to have a character limit and maximum value in both the `NumberField` and the `CurrencyField`.
- optional `maximumValue` prop for `NumberField` and `CurrencyField`.
- optional `characterLimit` prop for `NumberField` and `CurrencyField`.
<details> …

feat(CurrencyField, NumberField): Add maximumValue and characterLimit

---

packages/components/src/components/FormRow/index.tsx

This prevents nesting errors when using components based on `div`s in the label of a `FormRow` (example uses: checkboxes, radiobuttons).
- The label of the `FormRow` now renders as a `div` instead of a `p`.
<details> …

fix(FormRow): Change label to div

---

packages/components/src/components/FoldOut/index.tsx
packages/components/src/components/FoldOut/story.tsx
packages/components/src/components/FoldOut/style.tsx

- none
- Added a prop `excerptHeight` to determine to preview a part of the foldouts content
- none
<details> …

feat(FoldOut): Added excerpt mode to FoldOut component

---

packages/components/src/components/Notification/index.tsx
packages/components/src/components/Notification/story.tsx
packages/components/src/components/Notification/test.tsx

Makes it possible to use react nodes in the message via the children, just like the InlineNotification
- Added `data-testid` prop
- Made `message` prop optional
- Check if component has children and render them instead of the `message`
<details>
- Use `build`, `chore`, `ci`, `docs`, `perf`, `refactor`, `style`, or `test`  for …

feat(Notification): Allow react nodes as message via children

---

packages/components/src/components/Link/index.tsx
packages/components/src/components/Link/story.tsx
packages/components/src/components/Link/style.tsx
packages/components/src/components/Notification/story.tsx
packages/components/src/themes/MosTheme/MosTheme.theme.ts

BREAKING CHANGE: Adjusted Link theme object
resolves #605 
note: I removed the `fontSize` from the theme object as well and hard coded it as `inherit`. It wasn't being used in the anchor element anyway. The idea is that a Link should always be placed in a textual context, whether it be a `Text`, `Heading` or something else.
- Adjusted `Link` theme object
<details>
- Use …

feat(Link)!: Add severity colors to Link

---

packages/components/src/components/Checkbox/index.tsx

A margin was reserved in the `Checkbox` for its label, even when it wasn't rendered. This removes the margin when there is no label, fixing the spacing in the  `Table`.
- Remove extra margin when `Checkbox` has no label.
<details> …

fix(Checkbox): Remove margin for label when there is no label

---

packages/components/src/components/Checkbox/story.tsx
packages/components/src/components/Checkbox/style.tsx
packages/components/src/components/Checkbox/test.tsx
packages/components/src/themes/MosTheme/MosTheme.theme.ts

- Adds `checkedError` state to the Checkbox, this changes the `ThemeType`.
<details>
_Tip: make sure the first commit message is the one you want to merge, because that's the one …

feat!: Add checked error state to Checkbox

---

packages/components/src/components/Table/Row/index.tsx

- Missed the false condition of the `Branch` in `TableRow` when introducing the error state.
<details>
_Tip: make sure the first commit message is the one you want to …

fix(Table): Also show error state in undraggable rows

---

packages/components/src/components/Button/base/index.tsx
packages/components/src/components/IconButton/index.tsx
packages/components/src/components/Link/style.tsx

In some places, the `Link`, when used as a button, and `IconButton` components received box-shadows from legacy stylesheets. This PR explicitly sets them to none to prevent this.
- No more box-shadow for `Link` and `IconButton`
<details> …

fix: Prevent box-shadow on Link buttons and IconButtons

---

packages/components/src/components/Modal/index.tsx

- None
- Modal with media now has the title moved under the media on `size=small`
- None
<details>
_Tip: make …

chore: Moved title under media when small

---

packages/components/package.json

The pinned version of `bricks-assets` in `bricks` causes dependency errors when you have a higher version installed.
- `bricks-assets` version no longer pinned in `bricks` package
<details> …

fix: Adjust bricks-assets peerDependency version

---

packages/components/src/components/FileInput/index.tsx
packages/components/src/components/FileInput/story.tsx
packages/components/src/components/FileInput/style.tsx
packages/components/src/themes/MosTheme/MosTheme.theme.ts

**Based upon BIER-2951!**
- Added hover/disabled states to FileInput component
<details>
_Tip: make sure the first commit message is the one you want to merge, …

chore: Added hover/disabled states to FileInput component

---

packages/components/src/components/FileInput/index.tsx
packages/components/src/components/FileInput/story.tsx

- Added value and onError props to FileInput
<details> …

chore: Added value and onError props to FileInput

---

packages/components/src/components/TextualButton/index.tsx
packages/components/src/components/TextualButton/story.tsx
packages/components/src/themes/MosTheme/MosTheme.theme.ts

- None
- You can now style the hover color of the `TextualButton`
- none
<details>
_Tip: make sure the first …

feat: Added hover color to TextualButton

---

packages/components/src/components/Notification/index.tsx
packages/components/src/components/Notification/story.tsx
packages/components/src/components/Notification/style.tsx
packages/components/src/themes/MosTheme/MosTheme.theme.ts

- Adds 'default' to `Notification` themetype
<details> …

feat!: Add 'default' Notification variant

---

packages/components/src/components/Select/SelectOption.tsx
packages/components/src/components/Select/SelectSearch.tsx
packages/components/src/components/Select/index.tsx
packages/components/src/components/Select/story.tsx
packages/components/src/components/Select/test.tsx

- Select.Search now has to be passed in through search prop and is no longer rendered by default. This allows us to do custom rending for smaller selects (that only hold flags for instance) that do not require a searchbar.
- "testid"-input no longer exists by default, you can restore this behavior by giving the searchbar in the search prop a data-testid.
- None
- None
- [ x] Appropriate documentation has been written (check if not applicable).
<details>
- A …

feat!: Select.Search now has to be passed in through search prop

---

packages/components/src/components/ColorField/index.tsx
packages/components/src/components/ColorField/story.tsx

- Added initialValue prop and ResetButton
<details> …

chore: Added initialValue and ResetButton to ColorField

---

packages/components/src/components/ColorField/index.tsx
packages/components/src/components/ColorField/story.tsx

- Add validation to story
- Masking of input characters to component
- Styling changes to accomodate for feedback messages
<details>
_Tip: make sure the first commit …

chore: Added validation, errorstate and masking to ColorField

---

packages/components/src/components/ColorField/index.tsx
packages/components/src/components/ColorField/story.tsx

- Correct mouse cursor when disabled
<details> …

chore: Added disabled styling to ColorField

---

packages/components/src/components/ColorField/index.tsx
packages/components/src/components/ColorField/story.tsx

- Added support for transparency
<details> …

chore: Added transparency support to ColorField

---

packages/components/src/components/ColorField/index.tsx

- Because the onChange prop wasn't excluded from the original TextField PropsType the props get overloaded with the new type, resulting in a type like: `(value: string) => void | (value:string, event: Event) => void`. This results in an any on the `value` argument when using the callback because ts cannot determine which type should be used
<details>
- Use `build`, …

fix: Removed overload in the ColorField onChange

---

packages/components/package.json
packages/components/src/components/ColorDrop/index.tsx
packages/components/src/components/ColorField/index.tsx
packages/components/src/components/ColorField/story.tsx
packages/components/src/components/ColorPicker/index.tsx
packages/components/src/components/ColorPicker/story.tsx
packages/components/src/components/Popover/index.tsx
packages/components/src/index.ts

- Added new ColorPicker component to Bricks which implements react-color (custom version)
- Added ColorPicker to ColorField component
- Made the transparent swatch in the ColorPicker optional
<details> …

feat: Added ColorPicker component (to ColorField)

---

packages/components/src/components/Card/index.tsx
packages/components/src/components/Card/story.tsx
packages/components/src/components/FileInput/style.tsx
packages/components/src/components/FormRow/index.tsx
packages/components/src/components/FormRow/story.tsx
packages/components/src/components/FormRow/style.tsx
packages/components/src/components/NativeSelect/index.tsx
packages/components/src/components/NativeSelect/style.tsx
packages/components/src/components/Select/style.tsx
packages/components/src/utility/box/index.tsx

- None
- None
- The $grow prop wasnt properly applied for components with the flex mixin
- Added better defaults to Select, FormRow, Card and NativeSelect
- Added a few stories for FormRow
<details>
More info see …

fix: Added several default to flex components and fixed grow prop

---

packages/components/src/components/FileInput/index.tsx
packages/components/src/components/FormRow/story.tsx
packages/components/src/components/FormRow/style.tsx

- Fixed a few leftover flex properties for FormRow and FileInput
<details> …

fix: Formrow flex fixes

---

packages/components/src/themes/MosTheme/MosTheme.theme.ts

- Changes the line-heights of a few headings and body text formats to fit the 6px spatial system that UX adopted.
<details>
_Tip: make sure the first commit message is …

fix: Adjust line-heights to match 6px spacial system

---

packages/components/src/components/Text/index.tsx
packages/components/src/components/Text/story.tsx

- Strikthrough prop added to Text component
<details> …

chore: Added strikethrough support to Text component

---

packages/components/src/components/Heading/index.tsx
packages/components/src/components/Heading/story.tsx
packages/components/src/components/Text/index.tsx
packages/components/src/components/Text/story.tsx
packages/components/src/types/OffsetType/index.ts

- None
- Added color prop to Text and Heading that lets you make them white of color
- None
<details>
_Tip: …

feat: Added color prop to Text and Heading

---

packages/components/src/components/ColorField/index.tsx
packages/components/src/components/ColorField/story.tsx
packages/components/src/components/TextField/index.tsx

Fixed z-indexing issues and added a close callback to window. Also added box props to ColorPicker component.
<details>
_Tip: make sure the first commit message is the one you want to merge, because …

fix: Fixed z-indexing issues and added a close callback to window
